In [1]:
tour_selection = 'atp'

In [2]:
lefties = ['MARTERER',
           'EALA',
           'PERA',
           'TOWNSEND',
           'DAMM', 'ATMANE', 'SHANG', 'TABILO', 'KERBER', 'RYBAKOV',
'SHELTON',
'GASTON',
'MILLOT',
'MANNARINO',
'KRAJICEK',
'NIEMINEN',
'DELBONIS',
           'SUN',
'HUESLER',
           'TIEN',
'FERRARI',
'BERRER',
'KLAHN',
'ZEPPIERI',
'RINCON',
'BROADY',
'RAMOS-VINOLAS',
'NISHIOKA',
'NORRIE',
'MONTEIRO',
'BAGNIS',
'STRICKER',
'BOLT',
'BEMELMANS',
'BELLUCI',
'TABILO',
'DRAPER',
'VESELY',
'HUMBERT',
'BELLUCCI',
'KOEPFER',
'M.ZVEREV',
'KLIZAN',
'SHAPOVALOV',
'YOUNG',
'PELLA',
'DAMM',
'ZEBALLOS',
'LOPEZ',
'WEEKES',
           'VONDROUSOVA', 
           'KVITOVA',
           'FERNANDEZ',
           'TREVISAN',
'STEBE',
'MORAING',
'SHANG',
'FALLA',
'WILLIS',
'VERDASCO',
'SMITH',
'MELZER',
'QUIROZ',
'MOUTET',
'NADAL',
'ARNABOLDI',
           'F.LOPEZ',
           'PENNISTON',
           'RODIONOV',
           'HADDAD MAIA',
'MOLCAN']

In [3]:
usecols = [
 'PLAYER_HIT',
    'serve_quality_number',
 'CONTACT_X',
 'CONTACT_Y',
 'CONTACT_Z',
 'SPEED',
 'ON_NET_Y',
 'ON_NET_Z',
 'LET',
 'REBOUND_X',
 'REBOUND_Y',
 'NET_COORD_Y',
 'PLAYER_WIN',
 'match_id',
    'SCORE_POINT',
    'distance_from_sideline',
    'distance_from_side_or_center_line',
 'surface',
 'round',
 'serve_number',
 'point_id',
 'is_shot_serve',
 'shot_no',
 'is_shot_return',
 'is_last_shot',
 'rally_length',
 'PLAYER_WIN_NAME',
 'CONTACT_X_abs',
 'CONTACT_X_abs_from_baseline',
 'CONTACT_Y_abs',
 'CONTACT_Y_mirrored',
 'REBOUND_X_abs',
 'REBOUND_Y_mirrored',
 'ON_NET_Y_mirrored',
 'NET_COORD_Y_mirrored',
 'serve_direction',
 'serve_deuce_or_ad',
 'is_in_the_net',
 'is_shot_in',
 'set_no',
 'game_no',
 'point_no',
 'server_name',
 'is_break_point',
 'is_pressure_point',
 'shot_id']
usecols2 = ['CONTACT_X',
            'shot_id',
    'CONTACT_X_abs',
    'surface',
    'CONTACT_Y',
    'CONTACT_Y_abs',
    'CONTACT_Y_mirrored',
    'CONTACT_Z',
    'LET',
    'MAX_TRAJ_Z',
    'NET_COORD_Y',
    'NET_COORD_Y_mirrored',
    'ON_NET_Y',
    'ON_NET_Y_mirrored',
    'ON_NET_Z',
    'PLAYER_HIT',
    'PLAYER_WIN',
    'PLAYER_WIN_NAME',
    'player_win_name',
    'REBOUND_X',
    'REBOUND_X_abs',
    'is_shot_serve',
    'REBOUND_Y',
    'REBOUND_Y_mirrored',
    'SET_GAME_POINT',
    'SPEED',
    'SPIN',
    'distance',
    'distance_from_base_line',
    'distance_from_sideline',
    'game_no',
    'is_in_the_net',
    'is_last_shot',
    'is_shot_in',
    'match_id',
    'match_point_serve_id',
    'point_id',
    'previous_shot_speed',
    'rally_length',
    'receiver_name',
    'returner_accelerations',
    'returner_accelerations_window_max',
    'returner_change_of_possition_beginning_end_x',
                'returner_change_of_possition_beginning_end_y',
    'returner_decelerations_window_max',
    'returner_location_x',
    'returner_location_y',
    'returner_shot_distance_moved',
    'returner_speeds',
    'returner_speeds_avg',
    'returner_speeds_max',
    'round',
    'serve_deuce_or_ad',
    'serve_direction',
    'serve_number',
    'server_accelerations',
    'server_accelerations_window_max',
    'server_change_of_possition_beginning_end_x',
                'server_change_of_possition_beginning_end_y',
    'server_decelerations_window_max',
    'server_location_x',
    'server_location_y',
    'server_name',
    'server_shot_distance_moved',
    'server_speeds',
    'server_speeds_avg',
    'server_speeds_max',
    'set_no',
    'shot_no',
    'shot_time',
    'shot_time_end',
    'shot_time_start',
    'shot_type',
    'side',
    'speed_after_bounce',
    'speed_after_bounce_before_hit',
    'spinRPM',
    'Rally ending shot']
usecols_all = list(set(usecols).union(set(usecols2)))
#df = get_df_simple_wta()

In [4]:
def get_locations_at_shot(df, column_name):
    at_shot_locations =[]
    for server_location_values in df[column_name].tolist():
        float_values = [float(x) for x in server_location_values.strip('][').split(', ')]
        if len(float_values) > 0:
            at_shot_locations.append(float_values[0])
        else:
            at_shot_locations.append(np.nan)
    return at_shot_locations

In [5]:
def get_df_simple_wta_matches(tour='ATP'):
    
    import pandas as pd
    import psycopg2
    import os
    from sqlalchemy import create_engine


    import psycopg2
    from concurrent.futures import ProcessPoolExecutor
    import csv
    from datetime import datetime

    user='marin@gsa-he-db.postgres.database.azure.com'
    password='RV4vjA9xUxTjMc'
    host='gsa-he-db.postgres.database.azure.com'
    port='5432'
    database='postgres'
    user='marin'
    password=os.getenv('PG_PASSWORD')
    host='gsa-he-pgdb-17.postgres.database.azure.com'
    host='gsa-pg-data-production.postgres.database.azure.com'
    port='5432'
    port='5432'
    database='hawkeye'
    #user='marin@gsa-he-db.postgres.database.azure.com'
    password='RV4vjA9xUxTjMc'
    #host='gsa-he-db.postgres.database.azure.com'
    port='5432'
    #database='postgres'
    engine = create_engine(f'postgresql://{user}:{password}@{host}:5432/{database}')
    pg_conn = psycopg2.connect(f"dbname={database} user={user} host={host} password={password} port='5432'")
    #query = "SELECT * FROM wta_all_data"
    query = f'SELECT DISTINCT match_id, "PLAYER_HIT", surface FROM hawkeye_app.{tour}_matches_data'
    
    print(query)
    df = pd.read_sql(query, engine)
    df = df[(df.match_id.str.contains('2026|2025|2024|2023|2022|2021|2020|2019'))]
    #df = df[(df.match_id.str.contains('2022|2021|2020|2019'))]
    return df
    #df['point_no'] = df.point_id.apply(lambda x: float(x.split('_')[2]))
    #df = df.sort_values(by=['match_id', 'set_no', 'game_no', 'point_no', 'serve_number', 'shot_no'])

In [6]:
#d = pd.read_csv('/Users/marinkreso/Documents/gsa_post_match/leaderboard_new.csv')

In [7]:
#df.to_sql('he_leaderboard', engine, index=False)

In [8]:

df_combinations = get_df_simple_wta_matches(tour=tour_selection)
matches = df_combinations[df_combinations.surface.isin(['clay', 'hard', 'grass'])].groupby('PLAYER_HIT')['match_id'].nunique().reset_index()
matches_df = df_combinations[df_combinations.surface.isin(['clay', 'hard', 'grass'])].groupby('PLAYER_HIT')['match_id'].unique().reset_index()
#matches = df_combinations[df_combinations.surface.isin([ 'hard'])].groupby('PLAYER_HIT')['match_id'].nunique().reset_index()
#matches_df = df_combinations[df_combinations.surface.isin(['hard'])].groupby('PLAYER_HIT')['match_id'].unique().reset_index()
leftie_matches = df_combinations[df_combinations.PLAYER_HIT.isin(lefties)].match_id.to_list()

SELECT DISTINCT match_id, "PLAYER_HIT", surface FROM hawkeye_app.atp_matches_data

In [9]:
matches

    PLAYER_HIT  match_id
0    AGAMENONE         2
1      AGUILAR         1
2        AHMAD         1
3    AJDUKOVIC         1
4    AL JANAHI         1
..         ...       ...
464      ZHANG        84
465      ZHENG         3
466       ZHOU         2
467   ZHUKAYEV         2
468     ZVEREV       254

[469 rows x 2 columns]

In [10]:
matches = df_combinations[df_combinations.surface.isin(['clay', 'hard', 'grass'])].groupby('PLAYER_HIT')['match_id'].nunique().reset_index()
matches_df = df_combinations[df_combinations.surface.isin(['clay', 'hard', 'grass'])].groupby('PLAYER_HIT')['match_id'].unique().reset_index()
#matches = df_combinations[df_combinations.surface.isin([ 'hard'])].groupby('PLAYER_HIT')['match_id'].nunique().reset_index()
#matches_df = df_combinations[df_combinations.surface.isin(['hard'])].groupby('PLAYER_HIT')['match_id'].unique().reset_index()
leftie_matches = df_combinations[df_combinations.PLAYER_HIT.isin(lefties)].match_id.to_list()

In [11]:
df_combinations.match_id.nunique()

5571

In [12]:
def get_df_simple_wta_all(selected_match_ids, selected_player_name, tour='atp'):
    
    import pandas as pd
    import psycopg2
    import os
    from sqlalchemy import create_engine


    import psycopg2
    from concurrent.futures import ProcessPoolExecutor
    import csv
    from datetime import datetime

    
    #query = "SELECT * FROM wta_all_data"
    #cols = ','.join(list(f'\"{x}\"' for x in ['match_id', 'point_id', 'serve_number', 'serve_quality_number', 'game_no', 'shot_no', 'set_no', 'is_shot_in', 'PLAYER_HIT']))
    cols = ','.join(list(f'\"{x}\"' for x in usecols))
    query  = "SELECT %s FROM hawkeye_app.%s_all_data WHERE match_id IN (%s)" % ( cols, tour, ','.join([f"'{x}'" for x in selected_match_ids]))
    
    df = pd.read_sql(query, engine)
    
    df['point_no'] = df.point_id.apply(lambda x: float(x.split('_')[2]))
    df = df.sort_values(by=['match_id', 'set_no', 'game_no', 'point_no', 'serve_number', 'shot_no'])    
    return df

In [13]:
def preprocess(df, selected_player_name):
    df['point_no'] = df.point_id.apply(lambda x: float(x.split('_')[2]))
    df = df.sort_values(by=['match_id', 'set_no', 'game_no', 'point_no', 'serve_number', 'shot_no'])
    df['time_for_shot'] = df['shot_time_start'] - df['shot_time_start'].shift(1)
    #Simplified, because we only want to know for 3+ shots
    df['previous_speed_after_bounce_before_hit'] = df['speed_after_bounce_before_hit'].shift(1)
    df['is_shot_in_previous'] = df['is_shot_in'].shift(1) 
    df['distance_from_sideline_previous'] = df['distance_from_sideline'].shift(1) 
    #Simplified, because we only want to know for 3+ shots
    df['REBOUND_Y_mirrored_abs'] = abs(df['REBOUND_Y_mirrored'])
    df['CONTACT_Y_mirrored_abs'] = abs(df['CONTACT_Y_mirrored'])
    df['REBOUND_Y_mirrored_previous'] = df['REBOUND_Y_mirrored'].shift(1)
    df['REBOUND_Y_mirrored_next'] = np.where(df['is_last_shot'] == 1, np.nan, df['REBOUND_Y_mirrored'].shift(-1))
    df['CONTACT_Y_mirrored_previous'] = df.groupby('point_id')['CONTACT_Y_mirrored'].shift(1)
    df['CONTACT_Y_mirrored_previous_previous'] = df.groupby('point_id')['CONTACT_Y_mirrored'].shift(2)
    df['CONTACT_X_abs_previous'] = df.groupby('point_id')['CONTACT_X_abs'].shift(1)
    df['CONTACT_X_abs_previous_previous'] = df.groupby('point_id')['CONTACT_X_abs'].shift(2)
    df['shot_type_next'] = df.groupby('point_id')['shot_type'].shift(-1)
    df['REBOUND_X_abs_previous'] = df['REBOUND_X_abs'].shift(1)
    df['spinRPM_previous'] = df['spinRPM'].shift(1)
    df['CONTACT_Z_previous'] = df['CONTACT_Z'].shift(1)
    df['distance_from_bounce_to_hit'] = df['CONTACT_X_abs'] - df['REBOUND_X_abs_previous']
    df['distance_from_bounce_to_hit_previous'] = df['distance_from_bounce_to_hit'].shift(1)
    df['SPEED_previous'] = df['SPEED'].shift(1)
    df['cross_court_ball_approaching_number'] = abs((-1*df['CONTACT_Y_mirrored']) - df['CONTACT_Y_mirrored_previous'])
    df['is_approaching_shot_cross_court'] = np.where(df['CONTACT_Y_mirrored']*df['CONTACT_Y_mirrored_previous'] > 0, 1, 0)
    df['shot_direction'] = abs((-1*df['CONTACT_Y_mirrored']) - df['REBOUND_Y_mirrored'])
    df['is_shot_cross_court'] = np.where(df['CONTACT_Y_mirrored']*df['REBOUND_Y_mirrored'] > 0, 1, 0)
    df['is_shot_in_previous'] = df['is_shot_in'].shift(1) 
    df['distance_from_sideline_previous'] = df['distance_from_sideline'].shift(1) 
    df['sel_player_max_speed'] = np.where(df['server_name'] == selected_player_name, df['server_speeds_max'], df['returner_speeds_max'])
    df['sel_player_avg_speed'] = np.where(df['server_name'] == selected_player_name, df['server_speeds_avg'], df['returner_speeds_avg'])
    df['sel_player_shot_distance_moved'] = np.where(df['server_name'] == selected_player_name, df['server_shot_distance_moved'], df['returner_shot_distance_moved'])
    df['sel_player_change_of_possition_beginning_end_x'] = np.where(df['server_name'] == selected_player_name, df['server_change_of_possition_beginning_end_x'], df['returner_change_of_possition_beginning_end_x'])
    df['sel_player_change_of_possition_beginning_end_y'] = np.where(df['server_name'] == selected_player_name, df['server_change_of_possition_beginning_end_y'], df['returner_change_of_possition_beginning_end_y'])
    df['opponent_change_of_possition_beginning_end_x'] = np.where(df['server_name'] == selected_player_name, df['returner_change_of_possition_beginning_end_x'], df['server_change_of_possition_beginning_end_x'])
    df['sel_player_shot_distance_moved_previous'] = df['sel_player_shot_distance_moved'].shift(1) 
    df['sel_player_shot_distance_moved_previous'] = df['sel_player_shot_distance_moved'].shift(1) 
    if 'spinRPM' not in df.columns.tolist():
        df['spinRPM'] = np.nan
    #Simplified, because we only want to know for 3+ shots
    df['REBOUND_Y_mirrored_abs'] = abs(df['REBOUND_Y_mirrored'])
    df['CONTACT_Y_mirrored_abs'] = abs(df['CONTACT_Y_mirrored'])
    df['REBOUND_Y_mirrored_previous'] = df['REBOUND_Y_mirrored'].shift(1)
    df['REBOUND_Y_mirrored_next'] = np.where(df['is_last_shot'] == 1, np.nan, df['REBOUND_Y_mirrored'].shift(-1))
    df['CONTACT_Y_mirrored_previous'] = df['CONTACT_Y_mirrored'].shift(1)
    df['CONTACT_X_abs_previous'] = df['CONTACT_X_abs'].shift(1)
    df['REBOUND_X_abs_previous'] = df['REBOUND_X_abs'].shift(1)
    df['spinRPM_previous'] = df['spinRPM'].shift(1)
    df['time_for_shot_previous'] = df['time_for_shot'].shift(1)
    df['distance_from_bounce_to_hit'] = df['CONTACT_X_abs'] - df['REBOUND_X_abs_previous']
    df['cross_court_ball_approaching_number'] = abs((-1*df['CONTACT_Y_mirrored']) - df['CONTACT_Y_mirrored_previous'])
    df['is_approaching_shot_cross_court'] = np.where(df['CONTACT_Y_mirrored']*df['CONTACT_Y_mirrored_previous'] > 0, 1, 0)
    df['shot_direction'] = abs((-1*df['CONTACT_Y_mirrored']) - df['REBOUND_Y_mirrored'])
    df['is_shot_cross_court'] = np.where(df['CONTACT_Y_mirrored']*df['REBOUND_Y_mirrored'] > 0, 1, 0)
    df['is_shot_in_previous'] = df['is_shot_in'].shift(1) 
    df['distance_from_sideline_previous'] = df['distance_from_sideline'].shift(1) 
    df['sel_player_max_speed'] = np.where(df['server_name'] == selected_player_name, df['server_speeds_max'], df['returner_speeds_max'])
    df['sel_player_avg_speed'] = np.where(df['server_name'] == selected_player_name, df['server_speeds_avg'], df['returner_speeds_avg'])
    df['sel_player_decelerations_window_max'] = np.where(df['server_name'] == selected_player_name, df['server_decelerations_window_max'], df['returner_decelerations_window_max'])
    df['sel_player_accelerations_window_max'] = np.where(df['server_name'] == selected_player_name, df['server_accelerations_window_max'], df['returner_accelerations_window_max'])
    df['sel_player_shot_distance_moved'] = np.where(df['server_name'] == selected_player_name, df['server_shot_distance_moved'], df['returner_shot_distance_moved'])
    df['sel_player_change_of_possition_beginning_end_x'] = np.where(df['server_name'] == selected_player_name, df['server_change_of_possition_beginning_end_x'], df['returner_change_of_possition_beginning_end_x'])
    df['opponent_change_of_possition_beginning_end_x'] = np.where(df['server_name'] == selected_player_name, df['returner_change_of_possition_beginning_end_x'], df['server_change_of_possition_beginning_end_x'])
    df['sel_player_shot_distance_moved_previous'] = df['sel_player_shot_distance_moved'].shift(1) 
    df['sel_player_shot_distance_moved_previous'] = df['sel_player_shot_distance_moved'].shift(1) 
    df['server_location_start_x'] = [float(x.strip('][').split(', ')[0]) for x in df['server_location_x'].tolist()]
    df['returner_location_start_x'] = [float(x.strip('][').split(', ')[0]) for x in df['returner_location_x'].tolist()]
    df['opponent_decelerations_window_max'] = np.where(df['server_name'] != selected_player_name, df['server_decelerations_window_max'], df['returner_decelerations_window_max'])

    df['server_location_diff_x'] = [float(x.strip('][').split(', ')[0]) - float(x.strip('][').split(', ')[-1]) for x in df['server_location_x'].tolist()]
    df['returner_location_diff_x'] = [float(x.strip('][').split(', ')[0]) - float(x.strip('][').split(', ')[-1]) for x in df['returner_location_x'].tolist()]
    df['server_location_at_shot_x'] = get_locations_at_shot(df, 'server_location_x')
    df['returner_location_at_shot_x'] = get_locations_at_shot(df, 'returner_location_x')

    df['sel_player_location_at_shot_x'] = np.where(df['server_name'] == selected_player_name, df['server_location_at_shot_x'], df['returner_location_at_shot_x'])
    df['sel_player_location_at_shot_x_abs'] = df['sel_player_location_at_shot_x'].abs()
    df['opponent_location_at_shot_x'] = np.where(df['server_name'] == selected_player_name, df['returner_location_at_shot_x'], df['server_location_at_shot_x'])
    df['opponent_location_at_shot_x_abs'] = df['opponent_location_at_shot_x'].abs()
    df['sel_player_location_at_shot_x_abs_previous'] = df['sel_player_location_at_shot_x_abs'].shift(1)
    df['opponent_location_at_shot_x_abs_previous'] = df['opponent_location_at_shot_x_abs'].shift(1)
    df['sel_player_location_at_shot_x_abs_diff'] = df['sel_player_location_at_shot_x_abs_previous'] - df['sel_player_location_at_shot_x_abs']
    df['opponent_location_at_shot_x_abs_diff'] = df['opponent_location_at_shot_x_abs_previous'] - df['opponent_location_at_shot_x_abs']
    df['server_location_at_shot_y'] = get_locations_at_shot(df, 'server_location_y')
    df['returner_location_at_shot_y'] = get_locations_at_shot(df, 'returner_location_y')

    df['sel_player_location_at_shot_y'] = np.where(df['server_name'] == selected_player_name, df['server_location_at_shot_y'], df['returner_location_at_shot_y'])
    df['opponent_location_at_shot_y'] = np.where(df['server_name'] == selected_player_name, df['returner_location_at_shot_y'], df['server_location_at_shot_y'])
    df['opponent_location_at_shot_y_mirrored']  = np.where(df['opponent_location_at_shot_x'] > 0, -1*df['opponent_location_at_shot_y'], df['opponent_location_at_shot_y'])
    df['opponent_location_at_shot_y_mirrored_previous'] = df['opponent_location_at_shot_y_mirrored'].shift(1)
    df['server_location_at_shot_y'] = get_locations_at_shot(df, 'server_location_y')
    df['returner_location_at_shot_y'] = get_locations_at_shot(df, 'returner_location_y')

    df['sel_player_location_at_shot_y'] = np.where(df['server_name'] == selected_player_name, df['server_location_at_shot_y'], df['returner_location_at_shot_y'])
    df['opponent_location_at_shot_y'] = np.where(df['server_name'] == selected_player_name, df['returner_location_at_shot_y'], df['server_location_at_shot_y'])
    df['opponent_location_at_shot_y_mirrored']  = np.where(df['opponent_location_at_shot_x'] > 0, -1*df['opponent_location_at_shot_y'], df['opponent_location_at_shot_y'])
    df['opponent_location_at_shot_y_mirrored_previous'] = df['opponent_location_at_shot_y_mirrored'].shift(1)
    
    df['sel_player_location_at_shot_y_previous'] = df['sel_player_location_at_shot_y'].shift(1)
    df['sel_player_location_at_shot_y_abs_diff'] = abs(df['sel_player_location_at_shot_y_previous'] - df['sel_player_location_at_shot_y'])
    
    df['opponent_location_at_shot_y_previous'] = df['opponent_location_at_shot_y'].shift(1)
    df['opponent_player_location_at_shot_y_abs_diff'] = abs(df['opponent_location_at_shot_y_previous'] - df['opponent_location_at_shot_y'])

    df['sel_player_location_at_shot_x_y_abs_diff'] = df['sel_player_location_at_shot_x_abs_diff'] + df['sel_player_location_at_shot_y_abs_diff']
    df['distance_from_base_line_previous'] = df['distance_from_base_line'].shift(1)
    
    df['REBOUND_Y_mirrored_previous_previous'] = df['REBOUND_Y_mirrored_previous'].shift(1) 
    df['REBOUND_X_abs_previous_previous'] = df['REBOUND_X_abs_previous'].shift(1) 
    df['CONTACT_Y_mirrored_next'] = np.where(df['is_last_shot'] == 1, np.nan, df['CONTACT_Y_mirrored'].shift(-1))
    df['CONTACT_X_abs_next'] = np.where(df['is_last_shot'] == 1, np.nan, df['CONTACT_X_abs'].shift(-1))
    df['shot_id_next'] = df['shot_id'].shift(-1)
    df['shot_id_previous'] = df['shot_id'].shift(1)
    
    return df

In [14]:
def get_df_simple_wta(selected_match_ids, selected_player_name, tour='atp'):
    
    import pandas as pd
    import psycopg2
    import os
    from sqlalchemy import create_engine


    import psycopg2
    from concurrent.futures import ProcessPoolExecutor
    import csv
    from datetime import datetime

    
    #query = "SELECT * FROM wta_all_data"
    usecols_all_x = usecols_all + ['server_location_original_x', 'server_location_original_y']
    cols = ','.join(list(f'\"{x}\"' for x in usecols_all_x  if x != 'serve_quality_number'))
    query  = "SELECT %s FROM hawkeye_app.%s_all_movement_data WHERE match_id IN (%s)" % (cols, tour, ','.join([f"'{x}'" for x in selected_match_ids]))
    
    df = pd.read_sql(query, engine)
    
    df['point_no'] = df.point_id.apply(lambda x: float(x.split('_')[2]))
    df = df.sort_values(by=['match_id', 'set_no', 'game_no', 'point_no', 'serve_number', 'shot_no'])
    df['time_for_shot'] = df['shot_time_start'] - df['shot_time_start'].shift(1)
    #Simplified, because we only want to know for 3+ shots
    df['previous_speed_after_bounce_before_hit'] = df['speed_after_bounce_before_hit'].shift(1)
    df['is_shot_in_previous'] = df['is_shot_in'].shift(1) 
    df['distance_from_sideline_previous'] = df['distance_from_sideline'].shift(1) 
    #Simplified, because we only want to know for 3+ shots
    df['REBOUND_Y_mirrored_abs'] = abs(df['REBOUND_Y_mirrored'])
    df['CONTACT_Y_mirrored_abs'] = abs(df['CONTACT_Y_mirrored'])
    df['REBOUND_Y_mirrored_previous'] = df['REBOUND_Y_mirrored'].shift(1)
    df['REBOUND_Y_mirrored_next'] = np.where(df['is_last_shot'] == 1, np.nan, df['REBOUND_Y_mirrored'].shift(-1))
    df['CONTACT_Y_mirrored_previous'] = df.groupby('point_id')['CONTACT_Y_mirrored'].shift(1)
    df['CONTACT_Y_mirrored_previous_previous'] = df.groupby('point_id')['CONTACT_Y_mirrored'].shift(2)
    df['CONTACT_X_abs_previous'] = df.groupby('point_id')['CONTACT_X_abs'].shift(1)
    df['CONTACT_X_abs_previous_previous'] = df.groupby('point_id')['CONTACT_X_abs'].shift(2)
    df['shot_type_next'] = df.groupby('point_id')['shot_type'].shift(-1)
    df['REBOUND_X_abs_previous'] = df['REBOUND_X_abs'].shift(1)
    df['spinRPM_previous'] = df['spinRPM'].shift(1)
    df['CONTACT_Z_previous'] = df['CONTACT_Z'].shift(1)
    df['distance_from_bounce_to_hit'] = df['CONTACT_X_abs'] - df['REBOUND_X_abs_previous']
    df['distance_from_bounce_to_hit_previous'] = df['distance_from_bounce_to_hit'].shift(1)
    df['SPEED_previous'] = df['SPEED'].shift(1)
    df['cross_court_ball_approaching_number'] = abs((-1*df['CONTACT_Y_mirrored']) - df['CONTACT_Y_mirrored_previous'])
    df['is_approaching_shot_cross_court'] = np.where(df['CONTACT_Y_mirrored']*df['CONTACT_Y_mirrored_previous'] > 0, 1, 0)
    df['shot_direction'] = abs((-1*df['CONTACT_Y_mirrored']) - df['REBOUND_Y_mirrored'])
    df['is_shot_cross_court'] = np.where(df['CONTACT_Y_mirrored']*df['REBOUND_Y_mirrored'] > 0, 1, 0)
    df['is_shot_in_previous'] = df['is_shot_in'].shift(1) 
    df['distance_from_sideline_previous'] = df['distance_from_sideline'].shift(1) 
    df['sel_player_max_speed'] = np.where(df['server_name'] == selected_player_name, df['server_speeds_max'], df['returner_speeds_max'])
    df['sel_player_avg_speed'] = np.where(df['server_name'] == selected_player_name, df['server_speeds_avg'], df['returner_speeds_avg'])
    df['sel_player_shot_distance_moved'] = np.where(df['server_name'] == selected_player_name, df['server_shot_distance_moved'], df['returner_shot_distance_moved'])
    df['sel_player_change_of_possition_beginning_end_x'] = np.where(df['server_name'] == selected_player_name, df['server_change_of_possition_beginning_end_x'], df['returner_change_of_possition_beginning_end_x'])
    df['sel_player_change_of_possition_beginning_end_y'] = np.where(df['server_name'] == selected_player_name, df['server_change_of_possition_beginning_end_y'], df['returner_change_of_possition_beginning_end_y'])
    df['opponent_change_of_possition_beginning_end_x'] = np.where(df['server_name'] == selected_player_name, df['returner_change_of_possition_beginning_end_x'], df['server_change_of_possition_beginning_end_x'])
    df['sel_player_shot_distance_moved_previous'] = df['sel_player_shot_distance_moved'].shift(1) 
    df['sel_player_shot_distance_moved_previous'] = df['sel_player_shot_distance_moved'].shift(1) 
    if 'spinRPM' not in df.columns.tolist():
        df['spinRPM'] = np.nan
    #Simplified, because we only want to know for 3+ shots
    df['REBOUND_Y_mirrored_abs'] = abs(df['REBOUND_Y_mirrored'])
    df['CONTACT_Y_mirrored_abs'] = abs(df['CONTACT_Y_mirrored'])
    df['REBOUND_Y_mirrored_previous'] = df['REBOUND_Y_mirrored'].shift(1)
    df['REBOUND_Y_mirrored_next'] = np.where(df['is_last_shot'] == 1, np.nan, df['REBOUND_Y_mirrored'].shift(-1))
    df['CONTACT_Y_mirrored_previous'] = df['CONTACT_Y_mirrored'].shift(1)
    df['CONTACT_X_abs_previous'] = df['CONTACT_X_abs'].shift(1)
    df['REBOUND_X_abs_previous'] = df['REBOUND_X_abs'].shift(1)
    df['spinRPM_previous'] = df['spinRPM'].shift(1)
    df['time_for_shot_previous'] = df['time_for_shot'].shift(1)
    df['distance_from_bounce_to_hit'] = df['CONTACT_X_abs'] - df['REBOUND_X_abs_previous']
    df['cross_court_ball_approaching_number'] = abs((-1*df['CONTACT_Y_mirrored']) - df['CONTACT_Y_mirrored_previous'])
    df['is_approaching_shot_cross_court'] = np.where(df['CONTACT_Y_mirrored']*df['CONTACT_Y_mirrored_previous'] > 0, 1, 0)
    df['shot_direction'] = abs((-1*df['CONTACT_Y_mirrored']) - df['REBOUND_Y_mirrored'])
    df['is_shot_cross_court'] = np.where(df['CONTACT_Y_mirrored']*df['REBOUND_Y_mirrored'] > 0, 1, 0)
    df['is_shot_in_previous'] = df['is_shot_in'].shift(1) 
    df['distance_from_sideline_previous'] = df['distance_from_sideline'].shift(1) 
    df['sel_player_max_speed'] = np.where(df['server_name'] == selected_player_name, df['server_speeds_max'], df['returner_speeds_max'])
    df['sel_player_avg_speed'] = np.where(df['server_name'] == selected_player_name, df['server_speeds_avg'], df['returner_speeds_avg'])
    df['sel_player_decelerations_window_max'] = np.where(df['server_name'] == selected_player_name, df['server_decelerations_window_max'], df['returner_decelerations_window_max'])
    df['sel_player_accelerations_window_max'] = np.where(df['server_name'] == selected_player_name, df['server_accelerations_window_max'], df['returner_accelerations_window_max'])
    df['sel_player_shot_distance_moved'] = np.where(df['server_name'] == selected_player_name, df['server_shot_distance_moved'], df['returner_shot_distance_moved'])
    df['sel_player_change_of_possition_beginning_end_x'] = np.where(df['server_name'] == selected_player_name, df['server_change_of_possition_beginning_end_x'], df['returner_change_of_possition_beginning_end_x'])
    df['opponent_change_of_possition_beginning_end_x'] = np.where(df['server_name'] == selected_player_name, df['returner_change_of_possition_beginning_end_x'], df['server_change_of_possition_beginning_end_x'])
    df['sel_player_shot_distance_moved_previous'] = df['sel_player_shot_distance_moved'].shift(1) 
    df['sel_player_shot_distance_moved_previous'] = df['sel_player_shot_distance_moved'].shift(1) 
    df['server_location_start_x'] = [float(x.strip('][').split(', ')[0]) for x in df['server_location_x'].tolist()]
    df['returner_location_start_x'] = [float(x.strip('][').split(', ')[0]) for x in df['returner_location_x'].tolist()]
    df['opponent_decelerations_window_max'] = np.where(df['server_name'] != selected_player_name, df['server_decelerations_window_max'], df['returner_decelerations_window_max'])

    df['server_location_diff_x'] = [float(x.strip('][').split(', ')[0]) - float(x.strip('][').split(', ')[-1]) for x in df['server_location_x'].tolist()]
    df['returner_location_diff_x'] = [float(x.strip('][').split(', ')[0]) - float(x.strip('][').split(', ')[-1]) for x in df['returner_location_x'].tolist()]
    df['server_location_at_shot_x'] = get_locations_at_shot(df, 'server_location_x')
    df['returner_location_at_shot_x'] = get_locations_at_shot(df, 'returner_location_x')

    df['sel_player_location_at_shot_x'] = np.where(df['server_name'] == selected_player_name, df['server_location_at_shot_x'], df['returner_location_at_shot_x'])
    df['sel_player_location_at_shot_x_abs'] = df['sel_player_location_at_shot_x'].abs()
    df['opponent_location_at_shot_x'] = np.where(df['server_name'] == selected_player_name, df['returner_location_at_shot_x'], df['server_location_at_shot_x'])
    df['opponent_location_at_shot_x_abs'] = df['opponent_location_at_shot_x'].abs()
    df['sel_player_location_at_shot_x_abs_previous'] = df['sel_player_location_at_shot_x_abs'].shift(1)
    df['opponent_location_at_shot_x_abs_previous'] = df['opponent_location_at_shot_x_abs'].shift(1)
    df['sel_player_location_at_shot_x_abs_diff'] = df['sel_player_location_at_shot_x_abs_previous'] - df['sel_player_location_at_shot_x_abs']
    df['opponent_location_at_shot_x_abs_diff'] = df['opponent_location_at_shot_x_abs_previous'] - df['opponent_location_at_shot_x_abs']
    df['server_location_at_shot_y'] = get_locations_at_shot(df, 'server_location_y')
    df['returner_location_at_shot_y'] = get_locations_at_shot(df, 'returner_location_y')

    df['sel_player_location_at_shot_y'] = np.where(df['server_name'] == selected_player_name, df['server_location_at_shot_y'], df['returner_location_at_shot_y'])
    df['opponent_location_at_shot_y'] = np.where(df['server_name'] == selected_player_name, df['returner_location_at_shot_y'], df['server_location_at_shot_y'])
    df['opponent_location_at_shot_y_mirrored']  = np.where(df['opponent_location_at_shot_x'] > 0, -1*df['opponent_location_at_shot_y'], df['opponent_location_at_shot_y'])
    df['opponent_location_at_shot_y_mirrored_previous'] = df['opponent_location_at_shot_y_mirrored'].shift(1)
    df['server_location_at_shot_y'] = get_locations_at_shot(df, 'server_location_y')
    df['returner_location_at_shot_y'] = get_locations_at_shot(df, 'returner_location_y')

    df['sel_player_location_at_shot_y'] = np.where(df['server_name'] == selected_player_name, df['server_location_at_shot_y'], df['returner_location_at_shot_y'])
    df['opponent_location_at_shot_y'] = np.where(df['server_name'] == selected_player_name, df['returner_location_at_shot_y'], df['server_location_at_shot_y'])
    df['opponent_location_at_shot_y_mirrored']  = np.where(df['opponent_location_at_shot_x'] > 0, -1*df['opponent_location_at_shot_y'], df['opponent_location_at_shot_y'])
    df['opponent_location_at_shot_y_mirrored_previous'] = df['opponent_location_at_shot_y_mirrored'].shift(1)
    
    df['sel_player_location_at_shot_y_previous'] = df['sel_player_location_at_shot_y'].shift(1)
    df['sel_player_location_at_shot_y_abs_diff'] = abs(df['sel_player_location_at_shot_y_previous'] - df['sel_player_location_at_shot_y'])
    
    df['opponent_location_at_shot_y_previous'] = df['opponent_location_at_shot_y'].shift(1)
    df['opponent_player_location_at_shot_y_abs_diff'] = abs(df['opponent_location_at_shot_y_previous'] - df['opponent_location_at_shot_y'])

    df['sel_player_location_at_shot_x_y_abs_diff'] = df['sel_player_location_at_shot_x_abs_diff'] + df['sel_player_location_at_shot_y_abs_diff']
    df['distance_from_base_line_previous'] = df['distance_from_base_line'].shift(1)
    
    df['REBOUND_Y_mirrored_previous_previous'] = df['REBOUND_Y_mirrored_previous'].shift(1) 
    df['REBOUND_X_abs_previous_previous'] = df['REBOUND_X_abs_previous'].shift(1) 
    df['CONTACT_Y_mirrored_next'] = np.where(df['is_last_shot'] == 1, np.nan, df['CONTACT_Y_mirrored'].shift(-1))
    df['CONTACT_X_abs_next'] = np.where(df['is_last_shot'] == 1, np.nan, df['CONTACT_X_abs'].shift(-1))
    df['shot_id_next'] = df['shot_id'].shift(-1)
    df['shot_id_previous'] = df['shot_id'].shift(1)
    return df

In [15]:
import pandas as pd
import psycopg2
import os
from sqlalchemy import create_engine


import psycopg2
from concurrent.futures import ProcessPoolExecutor
import csv
from datetime import datetime
user='marin@gsa-he-db.postgres.database.azure.com'
password='RV4vjA9xUxTjMc'
host='gsa-he-db.postgres.database.azure.com'
port='5432'
database='postgres'
user='marin'
password=os.getenv('PG_PASSWORD')
host='gsa-he-pgdb-17.postgres.database.azure.com'
host='gsa-pg-data-production.postgres.database.azure.com'
port='5432'
database='hawkeye'
#user='marin@gsa-he-db.postgres.database.azure.com'
password='RV4vjA9xUxTjMc'
#host='gsa-he-db.postgres.database.azure.com'
port='5432'
#database='postgres'
engine = create_engine(f'postgresql://{user}:{password}@{host}:5432/{database}')
pg_conn = psycopg2.connect(f"dbname={database} user={user} host={host} password={password} port='5432'")

In [16]:
def define_neutral_shots(df, shot_no_min = 4, player_location_wide_max = 5, player_movement_speed_max = 3, player_acc_max = 5, player_distance_moved_before_contact_max = 5, player_dist_from_the_net_min = 10, 
                         player_dist_from_the_net_max = 17, incoming_ball_speed_before_contact_max=55, incoming_ball_speed_before_contact_min=20, previous_shot_speed_max = 150, previous_shot_speed_min = 60, 
                         rebound_depth_max = 11.6):
    
    #limit shot number
    df_neutral_shot_no = df[df['shot_no'] >= shot_no_min].copy()
    
    #neither player should be standing outside of the 5m from the middle line when the ball is hit
    df_neutral_not_too_wide = df_neutral_shot_no[(df_neutral_shot_no['sel_player_location_at_shot_y_mirrored'] <= player_location_wide_max)&(df_neutral_shot_no['opponent_location_at_shot_y_mirrored'] <= player_location_wide_max) &
                      (df_neutral_shot_no['sel_player_location_at_shot_y_mirrored'] >= -(player_location_wide_max))&(df_neutral_shot_no['opponent_location_at_shot_y_mirrored'] >= -(player_location_wide_max))]

    #Average speed of movement before the shot was less than X
    df_neutral_player_speed = df_neutral_shot_no[(df_neutral_shot_no['sel_player_avg_speed_previous'] <= player_movement_speed_max) & (df_neutral_shot_no['opponent_avg_speed_previous'] <= player_movement_speed_max)]
    
    #ACCELERATIONS SHOULD STILL BE TUNED
    #Average acceleration of movement before the shot was less than X (should be changed to average maybe)
    df_neutral_player_accelerations = df_neutral_shot_no[(df_neutral_shot_no['sel_player_accelerations_window_max_previous'] <= player_acc_max) & (df_neutral_shot_no['opponent_accelerations_window_max_previous'] <= player_acc_max)]

    #Average deceleration of movement before the shot was less than X (should be changed to average maybe)
    #df_neutral_player_deceleration = df_neutral_shot_no[(df_neutral_shot_no['sel_player_decelerations_window_max_previous'] >= -(sel_player_acc)) & (df_neutral_shot_no['opponent_decelerations_window_max_previous'] >= -(sel_player_acc))]

    #Distance a player makes before the contact
    df_neutral_player_distance_moved = df_neutral_shot_no[(df_neutral_shot_no['sel_player_shot_distance_moved_previous'] <= player_distance_moved_before_contact_max) & (df_neutral_shot_no['opponent_shot_distance_moved_previous'] <= player_distance_moved_before_contact_max)]

    #Player position not too much in the court
    df_neutral_player_too_close = df_neutral_shot_no[(df_neutral_shot_no['sel_player_location_at_shot_x_abs'] >= player_dist_from_the_net_min)&(df_neutral_shot_no['opponent_location_at_shot_x_abs'] >= player_dist_from_the_net_min)]

    #Player position not too far from the net
    df_neutral_player_too_far = df_neutral_shot_no[(df_neutral_shot_no['sel_player_location_at_shot_x_abs'] < player_dist_from_the_net_max)&(df_neutral_shot_no['opponent_location_at_shot_x_abs'] < player_dist_from_the_net_max)]

    #Speed of the incomming shot
    df_neutral_incomming_ball_speed = df_neutral_shot_no[(df_neutral_shot_no['speed_after_bounce_before_hit_previous'] <= incoming_ball_speed_before_contact_max) &(df_neutral_shot_no['speed_after_bounce_before_hit_previous'] >= incoming_ball_speed_before_contact_min)]
    df_neutral_shot_speed = df_neutral_shot_no[(df_neutral_shot_no['previous_shot_speed'] <= previous_shot_speed_max)&(df_neutral_shot_no['previous_shot_speed'] >= previous_shot_speed_min)]

    #If incomming ball bounces (very) close to the baseline it is not neutral ball
    df_neutral_bounce_too_deep = df_neutral_shot_no[df_neutral_shot_no['REBOUND_X_abs_previous'] < rebound_depth_max]

    df_neutral_situation_shots = df[df.index.isin(df_neutral_shot_no.index) & df.index.isin(df_neutral_not_too_wide.index) & df.index.isin(df_neutral_player_speed.index)
                                   & df.index.isin(df_neutral_player_distance_moved.index) & df.index.isin(df_neutral_player_too_close.index) & df.index.isin(df_neutral_player_too_far.index)
                                   & df.index.isin(df_neutral_incomming_ball_speed.index) & df.index.isin(df_neutral_player_accelerations.index) & df.index.isin(df_neutral_shot_speed.index) 
                                   & df.index.isin(df_neutral_bounce_too_deep.index)].copy()
    
    return df_neutral_situation_shots
def process_df(a, selected_player_name):
    a['opponent_shot_distance_moved'] = np.where(a['server_name'] != selected_player_name, a['server_shot_distance_moved'], a['returner_shot_distance_moved'])

    a['sel_player_location_at_shot_y_mirrored']  = np.where(a['sel_player_location_at_shot_x'] > 0, -1*a['sel_player_location_at_shot_y'], a['sel_player_location_at_shot_y'])
    a['sel_player_avg_speed_previous'] = a['sel_player_avg_speed'].shift(1)
    a['opponent_avg_speed'] = np.where(a['server_name'] == selected_player_name, a['returner_speeds_avg'], a['server_speeds_avg'])
    a['opponent_avg_speed_previous'] = a['opponent_avg_speed'].shift(1)
    a['sel_player_decelerations_window_max'] = np.where(a['server_name'] == selected_player_name, a['server_decelerations_window_max'], a['returner_decelerations_window_max'])
    a['sel_player_accelerations_window_max'] = np.where(a['server_name'] == selected_player_name, a['server_accelerations_window_max'], a['returner_accelerations_window_max'])
    a['sel_player_decelerations_window_max_previous'] = a['sel_player_decelerations_window_max'].shift(1)
    a['sel_player_accelerations_window_max_previous'] = a['sel_player_accelerations_window_max'].shift(1)
    a['opponent_accelerations_window_max'] = np.where(a['server_name'] == selected_player_name, a['returner_accelerations_window_max'], a['server_accelerations_window_max'])
    a['opponent_decelerations_window_max'] = np.where(a['server_name'] == selected_player_name, a['returner_decelerations_window_max'], a['server_decelerations_window_max'])
    a['opponent_accelerations_window_max_previous'] = a['opponent_accelerations_window_max'].shift(1)
    a['opponent_decelerations_window_max_previous'] = a['opponent_decelerations_window_max'].shift(1)
    a['opponent_shot_distance_moved_previous'] = a['opponent_shot_distance_moved'].shift(1)
    a['speed_after_bounce_before_hit_previous'] = a['speed_after_bounce_before_hit'].shift(1)
    df_neutral_shots = define_neutral_shots(a)
    a['is_neutral'] = 0
    a.loc[a.shot_id.isin(df_neutral_shots.shot_id), 'is_neutral'] = 1
    return a

In [17]:
women_clients = ['OSAKA',
 'HADDAD MAIA',
 'SWIATEK',
 'GAUFF',
 'PAVLYUCHENKOVA',
 'BOUZKOVA',
 'BADOSA',
 'PUTINTSEVA',
 'ANDREEVA',
 'RYBAKINA',
 'SAKKARI',
 'NAVARRO']

In [18]:
for x in ['PAUL',
'NAKASHIMA',
'BERGS',
'BAILLY',
'KECMANOVIC',
'ALTMAIER',
'SINNER',
'KORDA',
'TSITSIPAS']:
    print('-', x)

- PAUL
- NAKASHIMA
- BERGS
- BAILLY
- KECMANOVIC
- ALTMAIER
- SINNER
- KORDA
- TSITSIPAS

In [19]:
moi = ['Doha_2025_R16_Bergs_Medvedev', 'Rio_2025_R32_Fonseca_Muller',
       'Rio_2025_R32_Martinez_Ugo-Carabelli']
poi = ['BERGS', 'MEDVEDEV', 'FONSECA', 'MULLER', 'UGO CARABELLI',
       'MARTINEZ']

In [20]:
poi = ['NAKASHIMA', 'BONZI', 'PAUL', 'DIALLO', 'FILS', 'BORGES']
moi = ['Acapulco_2025_R32_Bonzi_Nakashima',
       'Acapulco_2025_R32_Diallo_Paul', 'Dubai_2025_R32_Fils_Borges']

In [21]:
poi = ['DJERE', 'MARTINEZ', 'MACHAC', 'ALTMAIER', 'GOFFIN', 'SHELTON',
       'TSITSIPAS', 'KHACHANOV']
moi = ['Santiago_2025_R16_Martinez_Djere',
       'Acapulco_2025_R16_Altmaier_Machac',
       'Acapulco_2025_R16_Goffin_Shelton',
       'Dubai_2025_R16_Tsitsipas_Khachanov']

In [22]:
moi = ['Acapulco_2025_SF_Machac_Nakashima',
       'Dubai_2025_SF_Griekspoor_Tsitsipas']
poi = ['NAKASHIMA', 'MACHAC', 'GRIEKSPOOR', 'TSITSIPAS']

In [23]:
moi = ['Acapulco_2025_SF_Machac_Nakashima',
       'Dubai_2025_SF_Griekspoor_Tsitsipas']
poi = ['NAKASHIMA', 'MACHAC', 'GRIEKSPOOR', 'TSITSIPAS']

In [24]:
poi = ['FEARNLEY', 'FONSECA', 'ZHANG', 'DIALLO']
moi = ['Indian_Wells_2025_1st_Fearnley_Fonseca',
       'Indian_Wells_2025_1st_Zhang_Diallo']

In [25]:
poi  = ['POPYRIN', 'BERGS', 'SEYBOTH WILD', 'TSITSIPAS', 'BOYER', 'PAUL',
       'DIALLO', 'FILS', 'MCDONALD', 'DAVIDOVICH FOKINA']
moi = ['Indian_Wells_2025_R64_Bergs_Popyrin',
       'Indian_Wells_2025_R64_Seyboth-Wild_Tsitsipas',
       'Indian_Wells_2025_R64_Paul_Boyer',
       'Indian_Wells_2025_R64_Fils_Diallo',
       'Indian_Wells_2025_1st_McDonald_Davidovich-Fokina']

In [26]:
poi  = ['DJOKOVIC', 'VAN DE ZANDSCHULP']
moi = ['Indian_Wells_2025_R64_Djokovic_van-de-Zandschulp']

In [27]:
import pandas as pd

In [28]:
moi = ['Geneva_2025_R32_Fucsovics_Bergs',
       'Geneva_2025_F_Hurkacz_Djokovic',
       'Geneva_2025_R16_Rinderknech_Hurkacz',
       'Geneva_2025_R32_Cazaux_Hurkacz',
       'Geneva_2025_R32_Rinderknech_Kecmanovic',
       'Geneva_2025_SF_Hurkacz_Ofner', 'Geneva_2025_QF_Fritz_Hurkacz',
       'Hamburg_2025_R16_Davidovich-fokina_Cobolli',
       'Hamburg_2025_R32_Etcheverry_Comesana',
       'Hamburg_2025_R32_Collignon_Nakashima',
       'Hamburg_2025_R32_Baez_Ugo-carabelli',
       'Hamburg_2025_R16_Ugo-carabelli_Etcheverry',
       'Hamburg_2025_QF_Etcheverry_Lehecka',
       'Hamburg_2025_F_Rublev_Cobolli',
       'Hamburg_2025_QF_Cobolli_Bautista-agut',
       'Hamburg_2025_R32_Davidovich-fokina_Monfils',
       'Hamburg_2025_R32_Altmaier_Auger-aliassime',
       'Hamburg_2025_R32_Martinez_Cerundolo',
       'Hamburg_2025_R32_Sachko_Cobolli',
       'Hamburg_2025_R16_Darderi_Nakashima',
       'Hamburg_2025_SF_Etcheverry_Cobolli']
poi = ['HURKACZ', 'DJOKOVIC', 'FRITZ', 'RINDERKNECH', 'CAZAUX', 'BERGS',
       'FUCSOVICS', 'KECMANOVIC', 'OFNER', 'RUBLEV', 'COBOLLI',
       'BAUTISTA AGUT', 'ETCHEVERRY', 'LEHECKA', 'NAKASHIMA', 'DARDERI',
       'DAVIDOVICH FOKINA', 'UGO CARABELLI', 'ALTMAIER',
       'AUGER ALIASSIME', 'BAEZ', 'COLLIGNON', 'MONFILS', 'COMESANA',
       'CERUNDOLO', 'MARTINEZ', 'SACHKO']

In [29]:
poi = ['GAUFF', 'BOUZKOVA']
moi = ['RG_2025_R32_Bouzkova_Gauff']

In [30]:
moi = ['Wimbledon_2025_R64_Osaka_Siniakova', 'Wimbledon_2025_1st_Osaka_Gibson']

poi = ['OSAKA', 'GIBSON', 'SINIAKOVA']

In [31]:
moi = ['Rome_2025_R64_Marozsan_Rublev',
       'Washington_2025_R32_Marozsan_Diallo',
       'Washington_2025_R64_Bonzi_Marozsan',
       'Miami_2025_1st_Monfils_Marozsan',
       'Geneva_2025_R16_Arnaldi_Marozsan',
       'Halle_2025_R16_Marozsan_Machac',
       'Hong_Kong_2025_R16_Rublev_Marozsan',
       'Hong_Kong_2025_R32_Safiullin_Marozsan',
       'Hong_Kong_2025_QF_Marozsan_Shang',
       'Munich_2025_R16_Humbert_Marozsan',
       'Munich_2025_R32_Engel_Marozsan',
       'Dubai_2025_R32_Marozsan_Bautista-Agut',
       'Eastbourne_2025_R32_Marozsan_Sonego',
       'Doha_2025_R16_Marozsan_Lehecka', 'Doha_2025_R32_Marozsan_Dougaz',
       'Indian_Wells_2025_R64_Marozsan_Mpetshi-Perricard',
       'Rotterdam_2025_R16_Rublev_Marozsan',
       'Monte_Carlo_2025_R64_Monfils_Marozsan']
poi = ['RUBLEV', 'MAROZSAN', 'DIALLO', 'BONZI', 'MONFILS', 'ARNALDI',
       'MACHAC', 'SAFIULLIN', 'SHANG', 'HUMBERT', 'ENGEL',
       'BAUTISTA AGUT', 'SONEGO', 'LEHECKA', 'DOUGAZ',
       'MPETSHI PERRICARD']

In [32]:
moi = [
       'Cincinnati_2025_R64_Basavareddy_Zverev',#
       'Cincinnati_2025_R64_Comesana_Darderi',#
       
       'Cincinnati_2025_R64_Mensik_Quinn',#
       'Cincinnati_2025_R64_Nakashima_Blockx']
poi = ['DARDERI']

In [33]:
moi = ['Cincinnati_2025_QF_Sinner_Auger-Aliassime']
poi = ['SINNER', 'AUGER ALIASSIME']

In [34]:
poi = ['SINNER', 'MENSIK', 'KOPRIVA', 'JARRY']
moi = ['US_Open_2025_1st_Sinner_Kopriva', 'US_Open_2025_1st_Mensik_Jarry']

In [35]:
moi = ['Chengdu_2025_R32_Bergs_Shang', 'Chengdu_2025_R32_Giron_Quinn',
       "Chengdu_2025_R32_Halys_O'Connell",
       'Hangzhou_2025_Q_Basavareddy_Onclin',
       'Hangzhou_2025_Q_Basavareddy_Zhukayev',
       'Hangzhou_2025_Q_Hijikata_Eubanks']
poi = ['BERGS', 'BASAVAREDDY', 'EUBANKS', "O'CONNELL", 'QUINN'
      , 'HALYS', 'SHANG', 'GIRON', 'ONCLIN', 'ZHUKAYEV', 'HIJIKATA']

In [36]:
poi = ['MEDJEDOVIC',
 'HUMBERT',
 'DAVIDOVICH FOKINA',
 'PAUL',
 'CERUNDOLO',
 'NAKASHIMA',
 'DE MINAUR',
 'MEDVEDEV',
 'ALTMAIER',
 'ZVEREV',
 'COLLIGNON',
 'TIAFOE']
moi = ['Queens_2026_R16_Medjedovic_Humbert',
 'Queens_2026_QF_Paul_Davidovich-Fokina',
 'Queens_2026_SF_Nakashima_Cerundolo',
 'Queens_2026_QF_de-Minaur_Nakashima',
 'Halle_2026_QF_Altmaier_Medvedev',
 'Halle_2026_QF_Zverev_Collignon',
 'Halle_2026_SF_Altmaier_Tiafoe'
      ]

In [37]:
poi = ['FILS', 'TIRANTE']
moi = ['Cincinnati_2026_QF_Tirante_Fils']

In [38]:
poi = ['FILS', 'TIAFOE', 'MPETSHI PERRICARD', 'BROOKSBY', 'KECMANOVIC', 'SHIMABUKURO']
moi = ['Cincinnati_2026_F_Fils_Tiafoe', 'Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby', 'Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']

In [39]:
import numpy as np
from CalculationsFinal import Calculations
opponents = []
dfs = []
#dfss = []
for i, x in enumerate(poi):
    selected_match_idsx = matches_df[matches_df.PLAYER_HIT == x].match_id.to_list()
    if selected_match_idsx:
        selected_match_idsx = list(selected_match_idsx[0])
    else:
        print('no matches')
        continue
    #selected_match_idsx = [x for x in selected_match_idsx if x not in leftie_matches]
    selected_match_idsx = [x for x in selected_match_idsx if '2026' in x or '2025' in x or '2022' in x or '2024' in x or '2023' in x or '2019' in x]
    #selected_match_idsx = [x for x in selected_match_idsx if '2024']
    l = pd.read_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new.parquet')
    existing_matches = l[l.player_name == x].match_id.to_list()
    # selected_match_idsx = [x for x in selected_match_idsx if '2024' in x or '2024' in x or '2024' in x]
    selected_match_idsx = [x for x in selected_match_idsx if x not in existing_matches]
    selected_match_idsx = [x for x in selected_match_idsx if x in moi]
    selected_match_idsx = [x.replace("'", "''") for x in selected_match_idsx]
    #selected_match_idsx = [x.replace("'", "''") for x in selected_match_idsx if x in moi]
    #moi = ['United_Cup_2024_R16_Swiatek_Garcia', 'AO_2024_1st_Garcia_Osaka']
    if not selected_match_idsx:
        continue
    #selected_match_idsx = [x for x in selected_match_idsx if '2023' in x.lower() or '2024' in x.lower()]
    
    
    #selected_match_idsx = ['Vienna_2023_SF_Medvedev_Tsitsipas', 'Cincinnati_2022_SF_Medvedev_Tsitsipas', 'ATP_Finals_2019_RR_MEDVEDEV_TSITSIPAS']
    if len(selected_match_idsx) < 10:
        print('Matches', x, len(selected_match_idsx))
    print(selected_match_idsx)
    if not selected_match_idsx:
        print(i, x, x in lefties, 'NO MATCHES')
        continue
    b = get_df_simple_wta_all(selected_match_idsx, x, tour=tour_selection.upper())
    b['CONTACT_Y_mirrored_next'] = np.where(b['is_last_shot'] == 1, np.nan, b['CONTACT_Y_mirrored'].shift(-1))
    a = get_df_simple_wta(selected_match_idsx, x, tour=tour_selection.upper())
    a = process_df(a, x)
    #dfss.append(a)
    
    #a = a[a.surface == 'grass']
    #b = b[b.surface == 'grass']
    if a.empty or b.empty:
        continue
    if x == 'WANG':
        calc = Calculations(x, a, b, True)
    else:
        calc = Calculations(x, a, b, x in lefties)
    dfs.append(calc.results_df)
    dfm = dfs[-1].drop_duplicates()

    #dfm[dfm.match_id != 'ALL'].to_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/leaderboard_haddad_new_wta3_all_shit3.csv', index=False)
    print(i, x, x in lefties)

Matches FILS 1
['Cincinnati_2026_F_Fils_Tiafoe']

/Users/marinkreso/Downloads/CalculationsFinal.py:354: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  strong_count = len(df_serves[(df_serves['PLAYER_WIN_NAME'] == Calculations.PLAYER_NAME) & (df.rally_length <= 7)])
/Users/marinkreso/Downloads/CalculationsFinal.py:366: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  weak_count = list(df_returns[(df_returns.PLAYER_WIN_NAME != df_returns.server_name) & (df.rally_length == 4)].point_id.unique())
/Users/marinkreso/Downloads/CalculationsFinal.py:1167: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  deep = len(df_returns[(df_returns.CONTACT_Y_mirrored_next.abs() >= 5.3) & (df.CONTACT_Y_mirrored*df.REBOUND_Y_mirrored > 0)]) # cross angled return

0 FILS False
Matches TIAFOE 1
['Cincinnati_2026_F_Fils_Tiafoe']

/Users/marinkreso/.pyenv/versions/3.10.12/envs/gsanew2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/marinkreso/.pyenv/versions/3.10.12/envs/gsanew2/lib/python3.10/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

1 TIAFOE False
Matches MPETSHI PERRICARD 1
['Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby']
2 MPETSHI PERRICARD False
Matches BROOKSBY 1
['Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby']
3 BROOKSBY False
Matches KECMANOVIC 1
['Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']
4 KECMANOVIC False
Matches SHIMABUKURO 1
['Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']
5 SHIMABUKURO False

In [40]:
#selected_match_idsx

In [41]:
selected_match_idsx

['Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']

In [42]:
l = pd.read_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new.parquet')

In [43]:
l[l.win_percent_first_serve > 100]

Empty DataFrame
Columns: [player_name, match_id, opponent_name, surface, serve_quality_second_deuce_wide, serve_quality_second_deuce_wide_total, serve_quality_second_deuce_t, serve_quality_second_deuce_t_total, serve_quality_second_ad_wide, serve_quality_second_ad_wide_total, serve_quality_second_ad_t, serve_quality_second_ad_t_total, first_return_in_percentage_pressure, first_return_in_percentage_pressure_total, first_return_in_percentage_break, first_return_in_percentage_break_total, first_return_win_percentage_pressure, first_return_win_percentage_pressure_total, first_return_win_percentage_break, first_return_win_percentage_break_total, win_percent_first_serve, win_percent_first_serve_total, win_percent_first_serve_pressure, win_percent_first_serve_pressure_total, win_percent_first_serve_break, win_percent_first_serve_break_total, percent_of_first_serves_within_04m_of_sideline, percent_of_first_serves_within_04m_of_sideline_total, percent_of_first_serves_within_04m_of_sideline_pressure, percent_of_first_serves_within_04m_of_sideline_pressure_total, percent_of_first_serves_within_04m_of_sideline_break, percent_of_first_serves_within_04m_of_sideline_break_total, first_serve_speed, first_serve_speed_total, first_serve_speed_before_bounce, first_serve_speed_before_bounce_total, first_serve_speed_after_bounce, first_serve_speed_after_bounce_total, first_serve_speed_deuce_w, first_serve_speed_deuce_w_total, first_serve_speed_deuce_t, first_serve_speed_deuce_t_total, first_serve_speed_ad_w, first_serve_speed_ad_w_total, first_serve_speed_ad_t, first_serve_speed_ad_t_total, first_serve_speed_decrease_break, first_serve_speed_decrease_break_total, first_serve_speed_decrease_break_deuce, first_serve_speed_decrease_break_deuce_total, first_serve_speed_decrease_break_ad, first_serve_speed_decrease_break_ad_total, avg_return_speed_opponent, avg_return_speed_opponent_total, percent_unreturned_first_serves, percent_unreturned_first_serves_total, percent_first_serves_won_in_two_to_four_shots, percent_first_serves_won_in_two_to_four_shots_total, first_serve_in_percentage, first_serve_in_percentage_total, first_serve_in_percentage_pressure, first_serve_in_percentage_pressure_total, first_serve_in_percentage_break, first_serve_in_percentage_break_total, first_serve_win_percentage_bh_deuce, first_serve_win_percentage_bh_deuce_total, first_serve_win_percentage_fh_deuce, first_serve_win_percentage_fh_deuce_total, first_serve_win_percentage_bh_ad, first_serve_win_percentage_bh_ad_total, first_serve_win_percentage_fh_ad, first_serve_win_percentage_fh_ad_total, win_percent_first_serve_rally_five_to_eight, win_percent_first_serve_rally_five_to_eight_total, win_percent_first_serve_rally_nine_plus, win_percent_first_serve_rally_nine_plus_total, percent_serve_points_won, percent_serve_points_won_total, percent_aces_per_serve_points, percent_aces_per_serve_points_total, avg_points_won_per_serve_game, avg_points_won_per_serve_game_total, avg_points_lost_per_serve_game, avg_points_lost_per_serve_game_total, serve_hold_rate, serve_hold_rate_total, serve_win_percentage_when_return_in, serve_win_percentage_when_return_in_total, serve_win_percentage_when_return_fast, serve_win_percentage_when_return_fast_total, serve_win_percentage_when_return_deep, serve_win_percentage_when_return_deep_total, serve_win_percentage_when_return_middle, serve_win_percentage_when_return_middle_total, serve_win_percentage_when_return_short, serve_win_percentage_when_return_short_total, percent_serve_pone_deuce_after_deuce_returned_middle, percent_serve_pone_deuce_after_deuce_returned_middle_total, percent_serve_pone_ad_after_ad_returned_middle, percent_serve_pone_ad_after_ad_returned_middle_total, ...]
Index: []

[0 rows x 609 columns]

In [44]:
l = pd.read_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new.parquet')
dfm = dfm[(dfm.match_id != 'ALL') & (~dfm.match_id.isin(l.match_id))]
#dfm = dfm[(dfm.match_id != 'ALL')]
dfm = dfm.append(l, ignore_index=True)
print(dfm.shape)
dfm = dfm.drop_duplicates(subset=['match_id', 'player_name'])
print(dfm.shape)
dfm.to_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new.parquet', index=False)
#dfm = None

(13178, 609)
(13178, 609)

In [45]:
#l[l.player_name == 'FONSECA'][['match_id', 'fh_amount']]

In [46]:
l[l.player_name == 'TSITSIPAS'].head(49)

,player_name,match_id,opponent_name,surface,serve_quality_second_deuce_wide,serve_quality_second_deuce_wide_total,serve_quality_second_deuce_t,serve_quality_second_deuce_t_total,serve_quality_second_ad_wide,serve_quality_second_ad_wide_total,...,movement_to_bh_direction_backward_avg_acc_total,movement_to_bh_direction_backward_avg_decc,movement_to_bh_direction_backward_avg_decc_total,movement_to_bh_direction_right_avg_speed,movement_to_bh_direction_right_avg_speed_total,movement_to_bh_direction_right_avg_acc,movement_to_bh_direction_right_avg_acc_total,movement_to_bh_direction_right_avg_decc,movement_to_bh_direction_right_avg_decc_total,sets
103,TSITSIPAS,Cincinnati_2026_R64_Tsitsipas_Auger-Aliassime,AUGER ALIASSIME,hard,6.00,3,3.20,5,5.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
127,TSITSIPAS,Cincinnati_2026_1st_Royer_Tsitsipas,ROYER,hard,6.00,3,2.38,8,2.86,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
211,TSITSIPAS,Rogers_cup_2026_R64_Tsitsipas_Fonseca,FONSECA,hard,7.00,2,3.09,11,3.00,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
225,TSITSIPAS,Rogers_cup_2026_1st_Damm_Tsitsipas,DAMM,hard,4.00,1,0.00,0,2.50,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
236,TSITSIPAS,Rogers_cup_2026_Q_Tsitsipas_Rice,RICE,hard,7.33,3,2.71,7,2.40,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
266,TSITSIPAS,Washington_2026_R32_de-Minaur_Tsitsipas,DE MINAUR,hard,5.29,7,3.40,10,2.29,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
303,TSITSIPAS,Gstaad_2026_QF_Rinderknech_Tsitsipas,RINDERKNECH,clay,7.75,4,2.62,8,3.67,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
304,TSITSIPAS,Gstaad_2026_SF_Shevchenko_Tsitsipas,SHEVCHENKO,clay,9.00,1,3.00,11,3.50,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
308,TSITSIPAS,Gstaad_2026_F_Tsitsipas_Collignon,COLLIGNON,clay,7.00,1,1.92,12,3.50,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
318,TSITSIPAS,Gstaad_2026_R16_Kym_Tsitsipas,KYM,clay,6.50,2,3.09,11,2.86,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
319,TSITSIPAS,Gstaad_2026_R32_Tsitsipas_Buse,BUSE,clay,7.00,3,3.33,6,5.00,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
489,TSITSIPAS,Wimbledon_2026_R64_Tsitsipas_Djokovic,DJOKOVIC,grass,4.00,1,3.00,3,2.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
500,TSITSIPAS,Wimbledon_2026_1st_Gaston_Tsitsipas,GASTON,grass,5.00,2,3.50,2,3.33,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
568,TSITSIPAS,Mallorca_2026_R32_Tsitsipas_Buse,BUSE,grass,7.20,5,3.00,2,3.38,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
677,TSITSIPAS,RG_2024_R16_Arnaldi_Tsitsipas,ARNALDI,clay,5.00,1,2.50,14,2.71,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
686,TSITSIPAS,RG_2026_R64_Arnaldi_Tsitsipas,ARNALDI,clay,6.25,4,2.82,11,2.63,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
710,TSITSIPAS,RG_2026_1st_Muller_Tsitsipas,MULLER,clay,4.00,1,3.00,1,2.67,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
730,TSITSIPAS,Geneva_2026_R16_Tsitsipas_Tien,TIEN,clay,5.43,7,3.67,3,4.00,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
751,TSITSIPAS,Geneva_2026_R32_Tsitsipas_Mpetshi-Perricard,MPETSHI PERRICARD,clay,4.00,1,3.00,4,2.56,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
828,TSITSIPAS,Rome_2026_1st_Tsitsipas_Machac,MACHAC,clay,5.50,2,3.00,8,2.80,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
867,TSITSIPAS,Madrid_2026_R16_Tsitsipas_Ruud,RUUD,clay,5.83,6,3.31,26,3.07,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
887,TSITSIPAS,Madrid_2026_R32_Tsitsipas_Merida,MERIDA,clay,7.00,1,3.22,9,2.83,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
896,TSITSIPAS,Madrid_2026_R64_Bublik_Tsitsipas,BUBLIK,clay,0.00,0,3.67,3,3.33,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
923,TSITSIPAS,Madrid_2026_1st_Kypson_Tsitsipas,KYPSON,clay,7.00,3,3.50,14,3.29,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1014,TSITSIPAS,Munich_2026_R32_Marozsan_Tsitsipas,MAROZSAN,clay,6.33,6,2.71,14,3.25,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1169,TSITSIPAS,Monte_Carlo_2026_R64_Cerundolo_Tsitsipas,CERUNDOLO,clay,8.00,1,3.40,10,3.55,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1369,TSITSIPAS,Miami_2026_R32_Fils_Tsitsipas,FILS,hard,7.75,4,3.00,5,3.40,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1401,TSITSIPAS,Miami_2026_R64_Tsitsipas_de-Minaur,DE MINAUR,hard,0.00,0,3.60,5,3.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1419,TSITSIPAS,Miami_2026_1st_Tsitsipas_Fery,FERY,hard,6.00,4,3.67,6,0.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1446,TSITSIPAS,United_Cup_2026_QF_Fritz_Tsitsipas,FRITZ,hard,6.50,4,2.25,4,2.00,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1447,TSITSIPAS,United_Cup_2026_RR_Harris_Tsitsipas,B.HARRIS,hard,6.50,2,2.33,6,2.50,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1448,TSITSIPAS,United_Cup_2026_RR_Tsitsipas_Mochizuki,MOCHIZUKI,hard,0.00,0,2.67,3,3.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1610,TSITSIPAS,Indian_Wells_2026_1st_Tsitsipas_Shapovalov,SHAPOVALOV,hard,4.83,6,4.00,1,1.50,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1650,TSITSIPAS,Dubai_2026_R32_Humbert_Tsitsipas,HUMBERT,hard,5.50,2,2.00,1,3.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1701,TSITSIPAS,Doha_2026_QF_Tsitsipas_Rublev,RUBLEV,hard,5.00,1,1.67,3,2.00,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1715,TSITSIPAS,Doha_2026_R16_Medvedev_Tsitsipas,MEDVEDEV,hard,10.00,1,0.00,0,2.50,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1734,TSITSIPAS,Doha_2026_R32_Echargui_Tsitsipas,ECHARGUI,hard,5.50,2,3.67,6,0.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1783,TSITSIPAS,Rotterdam_2026_R16_van-de-Zandschulp_Tsitsipas,VAN DE ZANDSCHULP,hard,5.00,2,3.22,9,3.75,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1801,TSITSIPAS,Rotterdam_2026_R32_Tsitsipas_Rinderknech,RINDERKNECH,hard,5.00,1,3.00,1,2.33,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2681,TSITSIPAS,US_Open_2025_R64_Tsitsipas_Altmaier,ALTMAIER,hard,5.57,7,2.80,20,3.00,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2742,TSITSIPAS,Winston_Salem_2025_R32_Tsitsipas_Bu,BU,hard,6.00,2,2.67,3,4.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2779,TSITSIPAS,Cincinnati_2025_R32_Tsitsipas_Bonzi,BONZI,hard,6.33,3,4.00,6,4.50,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2800,TSITSIPAS,Cincinnati_2025_R64_Tsitsipas_Marozsan,MAROZSAN,hard,6.00,1,3.20,5,3.00,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2925,TSITSIPAS,Rogers_cup_2025_R64_Tsitsipas_O'Connell,O'CONNELL,hard,5.00,1,3.67,9,3.33,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3515,TSITSIPAS,Halle_2025_R16_Michelsen_Tsitsipas,MICHELSEN,grass,6.33,3,3.33,3,3.00,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3532,TSITSIPAS,Halle_2025_R32_Tsitsipas_Darderi,DARDERI,grass,5.67,3,4.00,3,4.50,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3627,TSITSIPAS,RG_2025_R64_Gigante_Tsitsipas,GIGANTE,clay,4.91,11,4.00,1,3.00,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3651,TSITSIPAS,RG_2025_1st_Etcheverry_Tsitsipas,ETCHEVERRY,clay,8.00,1,3.43,7,4.17,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3794,TSITSIPAS,RG_combined_alcaraz,ALCARAZ,CLAY,6.00,2,1.00,5,2.00,4,...,3.0,-5.5,3.0,2.41,22.0,6.21,22.0,-5.77,22.0,1

In [47]:
dfm

,player_name,match_id,opponent_name,surface,serve_quality_second_deuce_wide,serve_quality_second_deuce_wide_total,serve_quality_second_deuce_t,serve_quality_second_deuce_t_total,serve_quality_second_ad_wide,serve_quality_second_ad_wide_total,...,movement_to_bh_direction_backward_avg_acc_total,movement_to_bh_direction_backward_avg_decc,movement_to_bh_direction_backward_avg_decc_total,movement_to_bh_direction_right_avg_speed,movement_to_bh_direction_right_avg_speed_total,movement_to_bh_direction_right_avg_acc,movement_to_bh_direction_right_avg_acc_total,movement_to_bh_direction_right_avg_decc,movement_to_bh_direction_right_avg_decc_total,sets
0,FILS,Cincinnati_2026_F_Fils_Tiafoe,TIAFOE,hard,7.50,2,2.71,7,3.29,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TIAFOE,Cincinnati_2026_F_Fils_Tiafoe,FILS,hard,5.50,2,3.00,13,2.33,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MPETSHI PERRICARD,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,BROOKSBY,hard,0.00,0,5.40,5,5.50,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BROOKSBY,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,MPETSHI PERRICARD,hard,0.00,0,2.75,4,2.67,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KECMANOVIC,Winston_Salem_2026_R64_Shimabukuro_Kecmanovic,SHIMABUKURO,hard,4.80,5,2.83,6,2.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13173,MCDONALD,ALL,ALL,ALL,4.95,37,3.07,44,3.24,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
13174,KECMANOVIC,ALL,ALL,ALL,5.17,69,2.77,295,2.88,198,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
13175,DRAPER,ALL,ALL,ALL,2.85,13,6.19,88,6.13,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
13176,PAUL,ALL,ALL,ALL,5.90,128,2.62,195,3.09,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
13177,BOLT,ALL,ALL,ALL,4.00,1,5.20,5,5.60,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [48]:
pd.read_parquet('/Users/marinkreso/Downloads/HE_add_match/gauff_clay_2026/New format.parquet').match_id.unique()

array(['Rome_2026_R64_Gauff_Valentova', 'Rome_2026_F_Gauff_Svitolina',
       'Rome_2026_R32_Gauff_Sierra', 'Rome_2026_QF_Gauff_Andreeva',
       'Rome_2026_SF_Cirstea_Gauff', 'RG_2026_R64_Gauff_Sherif',
       'RG_2026_R32_Gauff_Potapova', 'RG_2026_1st_Gauff_Townsend'],
      dtype=object)

poi = ['SVITOLINA', 'GAUFF']
moi = ['Rome_2026_QF_Svitolina_Rybakina', 'Rome_2026_SF_Swiatek_Svitolina', 'Rome_2026_F_Gauff_Svitolina', 'Rome_2026_R64_Gauff_Valentova', 'Rome_2026_F_Gauff_Svitolina',
       'Rome_2026_R32_Gauff_Sierra', 'Rome_2026_QF_Gauff_Andreeva',
       'Rome_2026_SF_Cirstea_Gauff', 'RG_2026_R64_Gauff_Sherif',
       'RG_2026_R32_Gauff_Potapova', 'RG_2026_1st_Gauff_Townsend']

In [49]:
import numpy as np
from CalculationsFinal5 import Calculations
opponents = []
dfs = []
#dfss = []
for i, x in enumerate(poi):
    selected_match_idsx = list(matches_df[matches_df.PLAYER_HIT == x].match_id.to_list()[0])
    #selected_match_idsx = [x for x in selected_match_idsx if x not in leftie_matches]
    selected_match_idsx = [x for x in selected_match_idsx if '2025' in x or '2026' in x or '2024' in x or '2023' in x ]
    #selected_match_idsx = [x for x in selected_match_idsx if '2022' in x]#" or '2024' in x or '2022' in x or '2023' in x ]
    #selected_match_idsx = [x for x in selected_match_idsx if '2025' in x or '2024' in x]
    #selected_match_idsx = [x for x in selected_match_idsx if '2024' in x]# in x or '2022' in x or '2023' in x]
    #selected_match_idsx = [x for x in selected_match_idsx if '2023' in x or '2023' in x]
    print(len(selected_match_idsx))
    #selected_match_idsx = [x.replace("'", "''") for x in selected_match_idsx if x not in existing]
    l = pd.read_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new_wta_with_sets_clean.parquet')
    existing_matches = l[l.player_name == x].match_id.to_list()
    # selected_match_idsx = [x for x in selected_match_idsx if '2024' in x or '2024' in x or '2024' in x]
    forbidden = [
        'AO_2025_1st_Djokovic_Basavareddy',
        'AO_2025_SF_Djokovic_Zverev',
        'AO_2025_QF_Djokovic_Alcaraz',
        'AO_2025_R16_Djokovic_Lehecka',
        'AO_2025_R32_Djokovic_Machac',
        'Indian_Wells_2023_R16_Medvedev_Zverev',
       'Indian_Wells_2023_R32_Ruusuvuori_Zverev',
       'Indian_Wells_2023_R64_Cachin_Zverev',
                'Monte_Carlo_2023_R16_Medvedev_Zverev',
       'Monte_Carlo_2023_R32_Bautista-Agut_Zverev',
       'Monte_Carlo_2023_R64_Bublik_Zverev'
        
    ]
    #existing_matches = []
    selected_match_idsx = [x.replace("'", "''") for x in selected_match_idsx if x not in existing_matches and x in moi and x not in forbidden]
    #selected_match_idsx = [x.replace("'", "''") for x in selected_match_idsx if x not in existing_matches and x not in forbidden]
    #selected_match_idsx = [x.replace("'", "''") for x in selected_match_idsx if x in moi]
    #moi = ['United_Cup_2024_R16_Swiatek_Garcia', 'AO_2024_1st_Garcia_Osaka']
    if not selected_match_idsx:
        continue
    #selected_match_idsx = [x for x in selected_match_idsx if '2023' in x.lower() or '2024' in x.lower()]
    
    print(selected_match_idsx)
    #selected_match_idsx = ['Vienna_2023_SF_Medvedev_Tsitsipas', 'Cincinnati_2022_SF_Medvedev_Tsitsipas', 'ATP_Finals_2019_RR_MEDVEDEV_TSITSIPAS']
    if len(selected_match_idsx) < 10:
        print('Matches', x, len(selected_match_idsx))
    
    b = get_df_simple_wta_all(selected_match_idsx, x, tour=tour_selection.upper())
    b['CONTACT_Y_mirrored_next'] = np.where(b['is_last_shot'] == 1, np.nan, b['CONTACT_Y_mirrored'].shift(-1))
    a = get_df_simple_wta(selected_match_idsx, x, tour=tour_selection.upper())
    a = process_df(a, x)
    #dfss.append(a)
    a = a.merge(b[['point_id', 'serve_number', 'shot_no', 'serve_quality_number']], on=['point_id', 'serve_number', 'shot_no'])
    calc = Calculations(x, a, b, x in lefties)
    dfs.append(calc.results_df)
    dfm = dfs[-1].drop_duplicates()
    for sets in [1, 2, 3, 4, 5]:
        calc = Calculations(x, a, b, x in lefties, sets=sets)
        dfs.append(calc.results_df)
        dfm = dfs[-1].drop_duplicates()
    
    #dfm[dfm.match_id != 'ALL'].to_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/leaderboard_haddad_new_wta_with_sets3.csv', index=False)
    print(i, x, x in lefties)
from util_leaderboard2 import clean_leaderboard_one_match_new
#clean_leaderboard_one_match_new(dfm[dfm.match_id != 'ALL']).to_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/leaderboard_haddad_new_wta_with_sets3_clean.csv', index=False)

139
['Cincinnati_2026_F_Fils_Tiafoe']
Matches FILS 1

/Users/marinkreso/Downloads/CalculationsFinal5.py:423: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  strong_count = len(df_serves[(df_serves['PLAYER_WIN_NAME'] == Calculations.PLAYER_NAME) & (df.rally_length < 7)])
/Users/marinkreso/Downloads/CalculationsFinal5.py:461: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  weak_count = list(df_returns[(df_returns.PLAYER_WIN_NAME != df_returns.server_name) & (df.rally_length == 4)].point_id.unique())
/Users/marinkreso/Downloads/CalculationsFinal5.py:433: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  strong_count = len(df_serves[(df_serves['PLAYER_WIN_NAME'] == Calculations.PLAYER_NAME) & (df.rally_length < 7)])
/Users/marinkreso/Downloads/CalculationsFinal5.py:445: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  weak_count = list(df_returns[(df_returns.PLAYER_WIN_NAME != df_returns.server_name) & (df.rally_length == 4)].point_id.unique())
/Users/marinkreso/Downloads/CalculationsFinal5.py:446: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  pushed_back = list(df_returns[(df_returns.CONTACT_X_abs_next > df_returns.CONTACT_X_abs_previous + 1) & (df.rally_length == 4)].point_id.unique())
/Users/marinkreso/Downloads/CalculationsFinal5.py:1262: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  deep = len(df_returns[(df_returns.CONTACT_Y_mirrored_next.abs() >= 5.3) & (df.CONTACT_Y_mirrored*df.REBOUND_Y_mirrored > 0)]) # cross angled return
/Users/marinkreso/.pyenv/versions/3.10.12/envs/gsanew2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/marinkreso/.pyenv/versions/3.10.12/envs/gsanew2/lib/python3.10/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

0 FILS False
83
['Cincinnati_2026_F_Fils_Tiafoe']
Matches TIAFOE 1
1 TIAFOE False
27
['Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby']
Matches MPETSHI PERRICARD 1
2 MPETSHI PERRICARD False
63
['Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby']
Matches BROOKSBY 1
3 BROOKSBY False
147
['Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']
Matches KECMANOVIC 1
4 KECMANOVIC False
6
['Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']
Matches SHIMABUKURO 1
5 SHIMABUKURO False

In [50]:
selected_match_idsx = list(matches_df[matches_df.PLAYER_HIT == x].match_id.to_list()[0])
#selected_match_idsx = [x for x in selected_match_idsx if x not in leftie_matches]
selected_match_idsx = [x for x in selected_match_idsx if '2025' in x or '2026' in x or '2024' in x or '2023' in x ]

In [51]:
selected_match_idsx

['Shanghai_2024_Q_Shapovalov_Shimabukuro',
 'Tokyo_2025_R16_Shimabukuro_Korda',
 'Winston_Salem_2026_R64_Shimabukuro_Kecmanovic',
 'Dallas_2026_R32_Shimabukuro_Kecmanovic',
 'Los_Cabos_2024_Q_Cobolli_Shimabukuro',
 'Tokyo_2025_Q_Shimabukuro_Navone']

In [52]:
l = pd.read_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new_wta_with_sets_clean.parquet')
existing_matches = l[l.player_name == x].match_id.to_list()

In [53]:
selected_match_idsx = [x.replace("'", "''") for x in selected_match_idsx if x not in existing_matches and x in moi and x not in forbidden]

In [54]:
selected_match_idsx

['Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']

In [55]:
selected_match_idsx

['Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']

In [56]:
selected_match_idsx

['Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']

In [57]:
l[l.match_id.isin(moi)]

Empty DataFrame
Columns: [player_name, match_id, opponent_name, surface, rally_long, rally_long_total, serve_plus_win, serve_plus_win_total, serve_quality_second_deuce_wide, serve_quality_second_deuce_wide_total, serve_quality_second_deuce_t, serve_quality_second_deuce_t_total, serve_quality_second_ad_wide, serve_quality_second_ad_wide_total, serve_quality_second_ad_t, serve_quality_second_ad_t_total, first_return_in_percentage_pressure, first_return_in_percentage_pressure_total, first_return_in_percentage_break, first_return_in_percentage_break_total, first_return_win_percentage_pressure, first_return_win_percentage_pressure_total, first_return_win_percentage_break, first_return_win_percentage_break_total, win_percent_first_serve, win_percent_first_serve_total, win_percent_first_serve_pressure, win_percent_first_serve_pressure_total, win_percent_first_serve_break, win_percent_first_serve_break_total, percent_of_first_serves_within_04m_of_sideline, percent_of_first_serves_within_04m_of_sideline_total, percent_of_first_serves_within_04m_of_sideline_pressure, percent_of_first_serves_within_04m_of_sideline_pressure_total, percent_of_first_serves_within_04m_of_sideline_break, percent_of_first_serves_within_04m_of_sideline_break_total, first_serve_speed, first_serve_speed_total, first_serve_speed_before_bounce, first_serve_speed_before_bounce_total, first_serve_speed_after_bounce, first_serve_speed_after_bounce_total, first_serve_speed_deuce_w, first_serve_speed_deuce_w_total, first_serve_speed_deuce_t, first_serve_speed_deuce_t_total, first_serve_speed_ad_w, first_serve_speed_ad_w_total, first_serve_speed_ad_t, first_serve_speed_ad_t_total, first_serve_speed_decrease_break, first_serve_speed_decrease_break_total, first_serve_speed_decrease_break_deuce, first_serve_speed_decrease_break_deuce_total, first_serve_speed_decrease_break_ad, first_serve_speed_decrease_break_ad_total, avg_return_speed_opponent, avg_return_speed_opponent_total, percent_unreturned_first_serves, percent_unreturned_first_serves_total, percent_first_serves_won_in_two_to_four_shots, percent_first_serves_won_in_two_to_four_shots_total, first_serve_in_percentage, first_serve_in_percentage_total, first_serve_in_percentage_pressure, first_serve_in_percentage_pressure_total, first_serve_in_percentage_break, first_serve_in_percentage_break_total, first_serve_win_percentage_bh_deuce, first_serve_win_percentage_bh_deuce_total, first_serve_win_percentage_fh_deuce, first_serve_win_percentage_fh_deuce_total, first_serve_win_percentage_bh_ad, first_serve_win_percentage_bh_ad_total, first_serve_win_percentage_fh_ad, first_serve_win_percentage_fh_ad_total, win_percent_first_serve_rally_five_to_eight, win_percent_first_serve_rally_five_to_eight_total, win_percent_first_serve_rally_nine_plus, win_percent_first_serve_rally_nine_plus_total, percent_serve_points_won, percent_serve_points_won_total, percent_aces_per_serve_points, percent_aces_per_serve_points_total, avg_points_won_per_serve_game, avg_points_won_per_serve_game_total, avg_points_lost_per_serve_game, avg_points_lost_per_serve_game_total, serve_hold_rate, serve_hold_rate_total, serve_win_percentage_when_return_in, serve_win_percentage_when_return_in_total, serve_win_percentage_when_return_fast, serve_win_percentage_when_return_fast_total, serve_win_percentage_when_return_deep, serve_win_percentage_when_return_deep_total, serve_win_percentage_when_return_middle, serve_win_percentage_when_return_middle_total, serve_win_percentage_when_return_short, serve_win_percentage_when_return_short_total, ...]
Index: []

[0 rows x 617 columns]

In [58]:
moi

['Cincinnati_2026_F_Fils_Tiafoe',
 'Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby',
 'Winston_Salem_2026_R64_Shimabukuro_Kecmanovic']

In [59]:
l.head(50)

,player_name,match_id,opponent_name,surface,rally_long,rally_long_total,serve_plus_win,serve_plus_win_total,serve_quality_second_deuce_wide,serve_quality_second_deuce_wide_total,...,movement_to_bh_direction_backward_avg_acc_total,movement_to_bh_direction_backward_avg_decc,movement_to_bh_direction_backward_avg_decc_total,movement_to_bh_direction_right_avg_speed,movement_to_bh_direction_right_avg_speed_total,movement_to_bh_direction_right_avg_acc,movement_to_bh_direction_right_avg_acc_total,movement_to_bh_direction_right_avg_decc,movement_to_bh_direction_right_avg_decc_total,sets
0,SWIATEK,Cincinnati_2026_SF_Pegula_Swiatek,PEGULA,hard,60.0,25,35.0,65,6.0,1,...,13,-4.02,13,2.12,35,3.67,35,-3.57,35,ALL
1,SWIATEK,Cincinnati_2026_SF_Pegula_Swiatek,PEGULA,hard,46.0,13,23.0,26,6.0,1,...,4,-3.70,4,2.08,16,3.81,16,-3.23,16,1
2,SWIATEK,Cincinnati_2026_SF_Pegula_Swiatek,PEGULA,hard,60.0,5,56.0,18,0.0,0,...,4,-3.42,4,2.12,8,3.80,8,-4.21,8,2
3,SWIATEK,Cincinnati_2026_SF_Pegula_Swiatek,PEGULA,hard,86.0,7,33.0,21,0.0,0,...,5,-4.74,5,2.19,11,3.37,11,-3.60,11,3
4,PEGULA,Cincinnati_2026_SF_Pegula_Swiatek,SWIATEK,hard,40.0,25,31.0,52,6.0,6,...,10,-2.66,10,2.16,54,3.55,54,-2.99,54,ALL
5,PEGULA,Cincinnati_2026_SF_Pegula_Swiatek,SWIATEK,hard,54.0,13,20.0,20,5.0,1,...,5,-2.96,5,2.35,28,3.40,28,-2.93,28,1
6,PEGULA,Cincinnati_2026_SF_Pegula_Swiatek,SWIATEK,hard,40.0,5,35.0,20,6.0,1,...,0,0.00,0,2.80,6,3.58,6,-2.63,6,2
7,PEGULA,Cincinnati_2026_SF_Pegula_Swiatek,SWIATEK,hard,14.0,7,42.0,12,6.0,4,...,5,-2.36,5,1.71,20,3.76,20,-3.20,20,3
8,FILS,Cincinnati_2026_SF_Cobolli_Fils,COBOLLI,hard,79.0,14,50.0,30,9.0,1,...,16,-3.60,16,2.14,17,4.34,17,-3.56,17,ALL
9,FILS,Cincinnati_2026_SF_Cobolli_Fils,COBOLLI,hard,89.0,9,56.0,18,0.0,0,...,11,-4.14,11,1.93,12,4.09,12,-3.95,12,1
10,FILS,Cincinnati_2026_SF_Cobolli_Fils,COBOLLI,hard,60.0,5,42.0,12,9.0,1,...,5,-2.42,5,2.62,5,4.92,5,-2.62,5,2
11,COBOLLI,Cincinnati_2026_SF_Cobolli_Fils,FILS,hard,21.0,14,24.0,17,4.0,2,...,22,-4.02,22,1.93,33,3.41,33,-3.60,33,ALL
12,COBOLLI,Cincinnati_2026_SF_Cobolli_Fils,FILS,hard,11.0,9,0.0,9,0.0,0,...,13,-3.87,13,1.71,21,3.04,21,-3.16,21,1
13,COBOLLI,Cincinnati_2026_SF_Cobolli_Fils,FILS,hard,40.0,5,50.0,8,4.0,2,...,9,-4.24,9,2.30,12,4.07,12,-4.37,12,2
14,NAKASHIMA,Cincinnati_2026_SF_Nakashima_Tiafoe,TIAFOE,hard,42.0,19,24.0,34,6.0,4,...,16,-2.83,16,1.69,35,3.15,35,-3.06,35,ALL
15,NAKASHIMA,Cincinnati_2026_SF_Nakashima_Tiafoe,TIAFOE,hard,46.0,13,19.0,16,6.0,3,...,12,-3.33,12,1.61,23,3.21,23,-3.39,23,1
16,NAKASHIMA,Cincinnati_2026_SF_Nakashima_Tiafoe,TIAFOE,hard,33.0,6,28.0,18,6.0,1,...,4,-1.35,4,1.83,12,3.03,12,-2.44,12,2
17,TIAFOE,Cincinnati_2026_SF_Nakashima_Tiafoe,NAKASHIMA,hard,58.0,19,48.0,42,5.0,3,...,12,-2.63,12,1.72,32,2.97,32,-2.46,32,ALL
18,TIAFOE,Cincinnati_2026_SF_Nakashima_Tiafoe,NAKASHIMA,hard,54.0,13,41.0,29,5.0,3,...,8,-2.33,8,1.59,21,2.22,21,-2.32,21,1
19,TIAFOE,Cincinnati_2026_SF_Nakashima_Tiafoe,NAKASHIMA,hard,67.0,6,62.0,13,0.0,0,...,4,-3.25,4,1.98,11,4.42,11,-2.73,11,2
20,FRITZ,Cincinnati_2026_QF_Fritz_Nakashima,NAKASHIMA,hard,53.0,17,44.0,34,4.0,3,...,19,-2.92,19,1.89,30,3.47,30,-2.72,30,ALL
21,FRITZ,Cincinnati_2026_QF_Fritz_Nakashima,NAKASHIMA,hard,33.0,6,64.0,11,4.0,2,...,2,-2.60,2,2.01,12,3.68,12,-2.32,12,1
22,FRITZ,Cincinnati_2026_QF_Fritz_Nakashima,NAKASHIMA,hard,100.0,3,33.0,9,5.0,1,...,10,-2.89,10,1.62,6,3.57,6,-2.92,6,2
23,FRITZ,Cincinnati_2026_QF_Fritz_Nakashima,NAKASHIMA,hard,50.0,8,36.0,14,0.0,0,...,7,-3.06,7,1.91,12,3.22,12,-3.02,12,3
24,NAKASHIMA,Cincinnati_2026_QF_Fritz_Nakashima,FRITZ,hard,47.0,17,41.0,51,6.0,7,...,18,-2.97,18,1.65,38,3.47,38,-3.04,38,ALL
25,NAKASHIMA,Cincinnati_2026_QF_Fritz_Nakashima,FRITZ,hard,67.0,6,33.0,18,4.0,2,...,4,-3.53,4,1.83,16,3.88,16,-3.37,16,1
26,NAKASHIMA,Cincinnati_2026_QF_Fritz_Nakashima,FRITZ,hard,0.0,3,50.0,18,6.0,3,...,8,-2.88,8,1.41,14,3.10,14,-2.76,14,2
27,NAKASHIMA,Cincinnati_2026_QF_Fritz_Nakashima,FRITZ,hard,50.0,8,40.0,15,7.0,2,...,6,-2.73,6,1.71,8,3.29,8,-2.86,8,3
28,BUSE,Barcelona_2026_R32_Buse_Moutet,MOUTET,clay,35.0,26,36.0,44,6.0,4,...,36,-3.99,36,2.31,42,3.10,42,-3.84,42,ALL
29,BUSE,Cincinnati_2026_R64_Walton_Buse,WALTON,hard,27.0,11,46.0,28,0.0,0,...,16,-3.47,16,1.99,21,4.21,21,-3.81,21,ALL
30,BUSE,Hamburg_2026_F_Buse_Paul,PAUL,clay,38.0,40,41.0,76,7.0,8,...,52,-3.96,52,2.00,92,3.84,92,-3.85,92,ALL
31,BUSE,Hamburg_2026_QF_Buse_Humbert,HUMBERT,clay,58.0,38,27.0,63,5.0,10,...,43,-3.84,43,2.22,55,4.15,55,-4.13,55,ALL
32,BUSE,Hamburg_2026_Q_Buse_Gaston,GASTON,clay,67.0,18,50.0,24,4.0,1,...,12,-3.74,12,2.25,20,4.71,20,-4.36,20,ALL
33,BUSE,Hamburg_2026_Q_Buse_Mcdonald,MCDONALD,clay,68.0,22,38.0,26,7.0,1,...,16,-4.06,16,2.03,29,4.52,29,-3.47,29,ALL
34,BUSE,Hamburg_2026_R32_Cobolli_Buse,COBOLLI,clay,40.0,15,46.0,41,6.0,2,...,15,-4.65,15,2.18,26,4.95,26,-4.21,26,ALL
35,BUSE,Hamburg_2026_SF_Kovacevic_Buse,KOVACEVIC,clay,100.0,6,74.0,19,5.0,3,...,8,-3.59,8,2.46,13,4.08,13,-3.17,13,ALL
36,BUSE,Indian-Wells_2026_Q_Buse_Draxl,DRAXL,hard,52.0,27,40.0,43,6.0,4,...,17,-3.51,17,1.87,37,4.01,37,-3.35,37,ALL
37,BUSE,Indian-Wells_2026_Q_Buse_Hijikata,HIJIKATA,hard,53.0,19,43.0,51,7.0,2,...,27,-3.09,27,2.08,38,3.59,38,-3.32,38,ALL
38,BUSE,Kitzbuhel_2026_R16_Feldbausch_Buse,FELDBAUSCH,clay,65.0,23,33.0,52,5.0,3,...,12,-3.43,12,2.20,45,4.47,45,-4.14,45,ALL
39,BUSE,Kitzbuhel_2026_R32_Kopriva_Buse,KOPRIVA,clay,52.0,27,47.0,45,5.0,6,...,28,-3.09,28,2.08,60,3.97,60,-3.27,60,ALL
40,BUSE,Madrid_2026_1st_Buse_Mannarino,MANNARINO,clay,64.0,14,45.0,33,7.0,1,...,15,-3.07,15,2.07,27,3.89,27,-3.56,27,ALL
41,BUSE,Mallorca_2026_R16_Kopriva_Buse,KOPRIVA,grass,20.0,10,41.0,27,6.0,2,...,14,-3.43,14,2.53,26,3.86,26,-3.63,26,ALL
42,BUSE,Marrakech_2026_R16_Buse_Ugo-Carabelli,UGO CARABELLI,clay,50.0,34,42.0,64,5.0,7,...,26,-3.37,26,1.95,70,3.60,70,-3.45,70,ALL
43,BUSE,Marrakech_2026_R32_Buse_Berrettini,BERRETTINI,clay,57.0,23,42.0,77,5.0,5,...,28,-3.59,28,2.23,56,3.60,56,-3.49,56,ALL
44,BUSE,Miami_2026_1st_Buse_Dzumhur,DZUMHUR,hard,48.0,29,42.0,65,6.0,5,...,31,-3.38,31,2.07,65,3.52,65,-3.46,65,ALL
45,BUSE,Miami_2026_Q_Buse_Echargui,ECHARGUI,hard,64.0,36,35.0,49,5.0,5,...,37,-3.31,37,1.85,61,3.65,61,-3.56,61,ALL
46,BUSE,Miami_2026_Q_Buse_Wong,WONG,hard,38.0,16,51.0,45,8.0,1,...,33,-3.14,33,2.02,37,3.72,37,-3.50,37,ALL
47,BUSE,Monte_Carlo_2026_Q_Buse_Goffin,GOFFIN,clay,41.0,29,33.0,42,5.0,4,...,20,-3.07,20,2.05,65,3.58,65,-3.23,65,ALL
48,BUSE,Queens_2026_R32_Buse_Giron,GIRON,grass,45.0,22,49.0,69,6.0,8,...,32,-2.87,32,2.06,39,3.86,39,-3.33,39,ALL
49,BUSE,Rio_2026_QF_Buse_Berrettini,BERRETTINI,clay,36.0,14,38.0,42,5.0,5,...,27,-3.50,27,2.00,30,3.14,30,-3.57,30,ALL

In [60]:
#dfs = []
dfs.append(calc.results_df)
dfm = dfs[-1].drop_duplicates()

In [61]:
dfm

,player_name,match_id,opponent_name,surface,rally_long,rally_long_total,serve_plus_win,serve_plus_win_total,serve_quality_second_deuce_wide,serve_quality_second_deuce_wide_total,...,movement_to_bh_direction_backward_avg_acc_total,movement_to_bh_direction_backward_avg_decc,movement_to_bh_direction_backward_avg_decc_total,movement_to_bh_direction_right_avg_speed,movement_to_bh_direction_right_avg_speed_total,movement_to_bh_direction_right_avg_acc,movement_to_bh_direction_right_avg_acc_total,movement_to_bh_direction_right_avg_decc,movement_to_bh_direction_right_avg_decc_total,sets
0,FILS,ALL,ALL,ALL,0.636364,11,0.391304,23,7.50,2,...,17,-4.052941,17,1.856000,25,4.020000,25,-4.072000,25,ALL
1,FILS,Cincinnati_2026_F_Fils_Tiafoe,TIAFOE,hard,0.636364,11,0.391304,23,7.50,2,...,17,-4.052941,17,1.856000,25,4.020000,25,-4.072000,25,ALL
2,FILS,ALL,ALL,ALL,0.833333,6,0.500000,10,7.00,1,...,9,-3.988889,9,1.925000,16,3.893750,16,-3.537500,16,1
3,FILS,Cincinnati_2026_F_Fils_Tiafoe,TIAFOE,hard,0.833333,6,0.500000,10,7.00,1,...,9,-3.988889,9,1.925000,16,3.893750,16,-3.537500,16,1
4,FILS,ALL,ALL,ALL,0.000000,2,0.250000,8,0.00,0,...,1,-4.200000,1,1.800000,4,3.850000,4,-5.325000,4,2
5,FILS,Cincinnati_2026_F_Fils_Tiafoe,TIAFOE,hard,0.000000,2,0.250000,8,0.00,0,...,1,-4.200000,1,1.800000,4,3.850000,4,-5.325000,4,2
6,FILS,ALL,ALL,ALL,0.666667,3,0.400000,5,8.00,1,...,7,-4.114286,7,1.680000,5,4.560000,5,-4.780000,5,3
7,FILS,Cincinnati_2026_F_Fils_Tiafoe,TIAFOE,hard,0.666667,3,0.400000,5,8.00,1,...,7,-4.114286,7,1.680000,5,4.560000,5,-4.780000,5,3
8,TIAFOE,ALL,ALL,ALL,0.363636,11,0.472222,36,5.50,2,...,14,-2.128571,14,1.654545,22,2.931818,22,-2.604545,22,ALL
9,TIAFOE,Cincinnati_2026_F_Fils_Tiafoe,FILS,hard,0.363636,11,0.472222,36,5.50,2,...,14,-2.128571,14,1.654545,22,2.931818,22,-2.604545,22,ALL
10,TIAFOE,ALL,ALL,ALL,0.166667,6,0.500000,12,0.00,0,...,7,-1.400000,7,1.483333,12,2.875000,12,-2.441667,12,1
11,TIAFOE,Cincinnati_2026_F_Fils_Tiafoe,FILS,hard,0.166667,6,0.500000,12,0.00,0,...,7,-1.400000,7,1.483333,12,2.875000,12,-2.441667,12,1
12,TIAFOE,ALL,ALL,ALL,1.000000,2,0.875000,8,5.50,2,...,3,-3.133333,3,1.950000,4,3.225000,4,-3.275000,4,2
13,TIAFOE,Cincinnati_2026_F_Fils_Tiafoe,FILS,hard,1.000000,2,0.875000,8,5.50,2,...,3,-3.133333,3,1.950000,4,3.225000,4,-3.275000,4,2
14,TIAFOE,ALL,ALL,ALL,0.333333,3,0.250000,16,0.00,0,...,4,-2.650000,4,1.800000,6,2.850000,6,-2.483333,6,3
15,TIAFOE,Cincinnati_2026_F_Fils_Tiafoe,FILS,hard,0.333333,3,0.250000,16,0.00,0,...,4,-2.650000,4,1.800000,6,2.850000,6,-2.483333,6,3
16,MPETSHI PERRICARD,ALL,ALL,ALL,0.428571,7,0.235294,17,0.00,0,...,5,-2.660000,5,1.822222,9,2.222222,9,-3.388889,9,ALL
17,MPETSHI PERRICARD,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,BROOKSBY,hard,0.428571,7,0.235294,17,0.00,0,...,5,-2.660000,5,1.822222,9,2.222222,9,-3.388889,9,ALL
18,MPETSHI PERRICARD,ALL,ALL,ALL,0.333333,3,0.285714,7,0.00,0,...,4,-2.800000,4,1.550000,6,1.666667,6,-2.916667,6,1
19,MPETSHI PERRICARD,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,BROOKSBY,hard,0.333333,3,0.285714,7,0.00,0,...,4,-2.800000,4,1.550000,6,1.666667,6,-2.916667,6,1
20,MPETSHI PERRICARD,ALL,ALL,ALL,0.500000,4,0.200000,10,0.00,0,...,1,-2.100000,1,2.366667,3,3.333333,3,-4.333333,3,2
21,MPETSHI PERRICARD,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,BROOKSBY,hard,0.500000,4,0.200000,10,0.00,0,...,1,-2.100000,1,2.366667,3,3.333333,3,-4.333333,3,2
22,BROOKSBY,ALL,ALL,ALL,0.571429,7,0.590909,22,0.00,0,...,5,-2.300000,5,1.707692,13,2.869231,13,-2.284615,13,ALL
23,BROOKSBY,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,MPETSHI PERRICARD,hard,0.571429,7,0.590909,22,0.00,0,...,5,-2.300000,5,1.707692,13,2.869231,13,-2.284615,13,ALL
24,BROOKSBY,ALL,ALL,ALL,0.666667,3,0.272727,11,0.00,0,...,4,-1.925000,4,1.950000,8,3.125000,8,-2.475000,8,1
25,BROOKSBY,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,MPETSHI PERRICARD,hard,0.666667,3,0.272727,11,0.00,0,...,4,-1.925000,4,1.950000,8,3.125000,8,-2.475000,8,1
26,BROOKSBY,ALL,ALL,ALL,0.500000,4,0.909091,11,0.00,0,...,1,-3.800000,1,1.320000,5,2.460000,5,-1.980000,5,2
27,BROOKSBY,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,MPETSHI PERRICARD,hard,0.500000,4,0.909091,11,0.00,0,...,1,-3.800000,1,1.320000,5,2.460000,5,-1.980000,5,2
28,KECMANOVIC,ALL,ALL,ALL,0.571429,14,0.400000,30,4.80,5,...,14,-2.892857,14,1.851613,31,3.419355,31,-3.116129,31,ALL
29,KECMANOVIC,Winston_Salem_2026_R64_Shimabukuro_Kecmanovic,SHIMABUKURO,hard,0.571429,14,0.400000,30,4.80,5,...,14,-2.892857,14,1.851613,31,3.419355,31,-3.116129,31,ALL
30,KECMANOVIC,ALL,ALL,ALL,0.200000,5,0.357143,14,4.00,1,...,4,-3.700000,4,1.916667,12,3.350000,12,-3.450000,12,1
31,KECMANOVIC,Winston_Salem_2026_R64_Shimabukuro_Kecmanovic,SHIMABUKURO,hard,0.200000,5,0.357143,14,4.00,1,...,4,-3.700000,4,1.916667,12,3.350000,12,-3.450000,12,1
32,KECMANOVIC,ALL,ALL,ALL,0.777778,9,0.437500,16,5.00,4,...,10,-2.570000,10,1.810526,19,3.463158,19,-2.905263,19,2
33,KECMANOVIC,Winston_Salem_2026_R64_Shimabukuro_Kecmanovic,SHIMABUKURO,hard,0.777778,9,0.437500,16,5.00,4,...,10,-2.570000,10,1.810526,19,3.463158,19,-2.905263,19,2
34,SHIMABUKURO,ALL,ALL,ALL,0.428571,14,0.470588,34,6.75,8,...,19,-3.036842,19,1.968750,32,4.018750,32,-3.518750,32,ALL
35,SHIMABUKURO,Winston_Salem_2026_R64_Shimabukuro_Kecmanovic,KECMANOVIC,hard,0.428571,14,0.470588,34,6.75,8,...,19,-3.036842,19,1.968750,32,4.018750,32,-3.518750,32,ALL
36,SHIMABUKURO,ALL,ALL,ALL,0.800000,5,0.307692,13,6.80,5,...,5,-2.760000,5,1.683333,12,4.216667,12,-3.458333,12,1
37,SHIMABUKURO,Winston_Salem_2026_R64_Shimabukuro_Kecmanovic,KECMANOVIC,hard,0.800000,5,0.307692,13,6.80,5,...,5,-2.760000,5,1.683333,12,4.216667,12,-3.458333,12,1
38,SHIMABUKURO,ALL,ALL,ALL,0.222222,9,0.571429,21,6.67,3,...,14,-3.135714,14,2.140000,20,3.900000,20,-3.555000,20,2
39,SHIMABUKURO,Winston_Salem_2026_R64_Shimabukuro_Kecmanovic,KECMANOVIC,hard,0.222222,9,0.571429,21,6.67,3,...,14,-3.135714,14,2.140000,20,3.900000,20,-3.555000,20,2

In [62]:
dfm.match_id.nunique()

4

In [63]:
l = pd.read_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new_wta_with_sets_clean.parquet')
dfm = dfm[(dfm.match_id != 'ALL') & (~dfm.match_id.isin(l.match_id))]
dfm = dfm[(dfm.match_id != 'ALL')]
print(dfm.shape)
dfm = clean_leaderboard_one_match_new(dfm).append(l, ignore_index=True)
dfm = dfm.drop_duplicates(subset=['match_id', 'player_name', 'sets'])
print(dfm.shape)
dfm.to_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new_wta_with_sets_clean.csv', index=False)
dfm.to_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_movement.csv', index=False)

(20, 617)
shit
1     39
3     50
5     25
7     40
9     47
11    50
13    88
15    25
17    24
19    29
21    20
23    59
25    27
27    91
29    40
31    36
33    44
35    47
37    31
39    57
Name: serve_plus_win, dtype: int64
after shit
(22996, 617)

In [64]:
dfm.shape

(22996, 617)

In [65]:
dfm.to_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new_wta_with_sets_clean.csv', index=False)
dfm.to_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_movement.csv', index=False)

In [66]:
##dfm.to_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new_wta_with_sets_clean.csv', index=False)
#dfm.to_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_movement.csv', index=False)

In [67]:
l1 = pd.read_csv('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new_wta_with_sets_clean.csv')

In [68]:
l1['sets'] = l1['sets'].astype(str)

In [69]:
l1.to_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new_wta_with_sets_clean.parquet', index=False)

In [70]:
l1.to_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_movement.parquet', index=False)

In [71]:
#l1[l1.match_id == 'RG_2026_R64_Jovic_Navarro'].to_parquet('aggregated_data.parquet')

In [72]:
l = pd.read_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new.parquet')

In [73]:
dfm.head(10)

,player_name,match_id,opponent_name,surface,rally_long,rally_long_total,serve_plus_win,serve_plus_win_total,serve_quality_second_deuce_wide,serve_quality_second_deuce_wide_total,...,movement_to_bh_direction_backward_avg_acc_total,movement_to_bh_direction_backward_avg_decc,movement_to_bh_direction_backward_avg_decc_total,movement_to_bh_direction_right_avg_speed,movement_to_bh_direction_right_avg_speed_total,movement_to_bh_direction_right_avg_acc,movement_to_bh_direction_right_avg_acc_total,movement_to_bh_direction_right_avg_decc,movement_to_bh_direction_right_avg_decc_total,sets
0,FILS,Cincinnati_2026_F_Fils_Tiafoe,TIAFOE,hard,64.0,11,39.0,23,7.0,2,...,17,-4.05,17,1.86,25,4.02,25,-4.07,25,ALL
1,FILS,Cincinnati_2026_F_Fils_Tiafoe,TIAFOE,hard,83.0,6,50.0,10,7.0,1,...,9,-3.99,9,1.93,16,3.89,16,-3.54,16,1
2,FILS,Cincinnati_2026_F_Fils_Tiafoe,TIAFOE,hard,0.0,2,25.0,8,0.0,0,...,1,-4.20,1,1.80,4,3.85,4,-5.33,4,2
3,FILS,Cincinnati_2026_F_Fils_Tiafoe,TIAFOE,hard,67.0,3,40.0,5,8.0,1,...,7,-4.11,7,1.68,5,4.56,5,-4.78,5,3
4,TIAFOE,Cincinnati_2026_F_Fils_Tiafoe,FILS,hard,36.0,11,47.0,36,5.0,2,...,14,-2.13,14,1.65,22,2.93,22,-2.60,22,ALL
5,TIAFOE,Cincinnati_2026_F_Fils_Tiafoe,FILS,hard,17.0,6,50.0,12,0.0,0,...,7,-1.40,7,1.48,12,2.87,12,-2.44,12,1
6,TIAFOE,Cincinnati_2026_F_Fils_Tiafoe,FILS,hard,100.0,2,88.0,8,5.0,2,...,3,-3.13,3,1.95,4,3.23,4,-3.28,4,2
7,TIAFOE,Cincinnati_2026_F_Fils_Tiafoe,FILS,hard,33.0,3,25.0,16,0.0,0,...,4,-2.65,4,1.80,6,2.85,6,-2.48,6,3
8,MPETSHI PERRICARD,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,BROOKSBY,hard,43.0,7,24.0,17,0.0,0,...,5,-2.66,5,1.82,9,2.22,9,-3.39,9,ALL
9,MPETSHI PERRICARD,Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby,BROOKSBY,hard,33.0,3,29.0,7,0.0,0,...,4,-2.80,4,1.55,6,1.67,6,-2.92,6,1

In [74]:
import pandas as pd
l = pd.read_parquet('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/leaderboard_haddad_new.parquet')
import re
data = []
clay_tournaments = ['Rome', 'Strasbourg', 'RG', 'Madrid', 'Monte Carlo', 'Monte_Carlo', 'Munich', 'Barcelona', 'Umag', 'Kitzbuhel', 'Bastad', 'Gstaad', 'Geneva', 'Monte-Carlo', 'Hamburg', 'Buenos_Aires', 'Lyon', 'Rio',  
                    'Santiago', 'Buenos_Aires', 'Houston', 'Marrakech', 'Bucharest', 'Charleston', 'Hamburg', 'Barcelona', 'Munich']
grass_tournaments = ['Wimbledon', 'Hertogenbosh', 'Halle', 'Queens', 'Stuttgart', 'Malorca', 'Mallorca', 'Hertogenbosch', 'Eastbourne', 'Berlin']
clay_tournaments = [x.upper() for x in clay_tournaments]
grass_tournaments = [x.upper() for x in grass_tournaments]
#forbidden = [
#        'AO_2025_1st_Djokovic_Basavareddy',
#        'AO_2025_SF_Djokovic_Zverev',
#        'AO_2025_QF_Djokovic_Alcaraz',
#        'AO_2025_R16_Djokovic_Lehecka',
#        'AO_2025_R32_Djokovic_Machac'
#    ]
forbidden = ['Indian_Wells_2023_R16_Medvedev_Zverev',
       'Indian_Wells_2023_R32_Ruusuvuori_Zverev',
       'Indian_Wells_2023_R64_Cachin_Zverev',
                'Monte_Carlo_2023_R16_Medvedev_Zverev',
       'Monte_Carlo_2023_R32_Bautista-Agut_Zverev',
       'Monte_Carlo_2023_R64_Bublik_Zverev']
l = l[~l.match_id.isin(forbidden)]
for _, row in l[l.match_id != 'ALL'][['match_id', 'player_name', 'opponent_name', 'surface']].drop_duplicates().iterrows():
    #if not row['match_id'] in df_all.match_id.unique():
    #    continue
    if 'combined' in row['match_id']:
        continue
    pattern = re.compile(r'(.+?)_(\d{4})_(.+)')
    # Use the pattern to match and extract the partssss
    matches = pattern.match(row['match_id'])
    parts = matches.groups()

    tournament = parts[0].replace('_', ' ').strip().upper()
    if tournament == 'MONTREAL' or tournament == 'TORONTO':
        tournament = 'ROGERS CUP'
    year = parts[1]
    
    if tournament in grass_tournaments and row['surface'] != 'grass':
        row['surface'] = 'grass'
        if tournament.lower() == 'stuttgart' and ('swiatek' in row['match_id'].lower() or  'rybakina' in row['match_id'].lower()) :
            row['surface'] = 'clay'
            

        #print(row['match_id'], 'grass')
    if tournament in clay_tournaments and row['surface'] != 'clay':
        row['surface'] = 'clay'
        #print(row['match_id'], 'clay')
    if tournament == 'RG':
        tournament = 'ROLAND GARROS'
    if tournament == 'AO':
        tournament = 'AUSTRALIAN OPEN'
    if row['player_name'] == 'DJOKOVIC' and year != '2025':
        continue
    
    try:
        round_number, _, _ = parts[2].replace('Haddad_Maia', 'Haddad-Maia').replace('Carreno_Busta', 'Carreno-Busta').replace('Bautista_Agut', 'Bautista-Agut').replace('van_de_Zandschulp', 'van-de-Zandschulp').replace('Davidovich_Fokina', 'Davidovich-Fokina').split('_')
        data.append({
            'PLAYER': row['player_name'],
            'OPPONENT': row['opponent_name'],
            'TOURNAMENT': tournament.replace(' ', '-').replace('_', '-'),
            'YEAR': year,
            'ROUND': round_number,
            'SURFACE': row['surface'],
            'FORMAT': 'HE',
            'match_id': row['match_id'],
        })
    except:
        print(parts)
        continue
import json
with open('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/all_data2.json', 'w') as f:
    json.dump(data, f, indent=4)

('Madrid', '2022', 'Q_Moro_Canas_Musetti')
('Fort', '2023', '2022_SF_Swiatek_Sabalenka')
('Fort', '2023', '2022_SF_Swiatek_Sabalenka')
('Rogers_cup', '2022', 'R32_de_Minaur_Dimitrov')
('Toronto', '2022', 'SF_Gauff__Halep')
('Madrid', '2022', 'R32_de_Minaur_Sinner')
('Monte-Carlo', '2023', '2022_SF_Sinner_Rune')
('Indian_Wells', '2022', 'R16_Fritz_de_Minaur')
('Monte-Carlo', '2023', '2022_SF_Sinner_Rune')
('Madrid', '2021', 'R16_Thiem_de_Minaur')
('Indian_Wells', '2021', 'R64_Vukic_de_Minaur')
('Paris', '2021', 'R64_Popyrin_de_Minaur')
('Indian_Wells', '2021', '1st_Olivo_Carballes_Baena')
('Cincinnati', '2021', 'R32_Monfils_de_Minaur')
('Madrid', '2022', 'R64_Gimeno_Valero_Monfils')
('Rome', '2021', 'R64_Carballes_Baena_Norrie')
('Madrid', '2021', 'Q_Zapata_Miralles_Delbonis')
('Rogers_cup', '2021', 'R32_de_Minaur_Basilashvili')
('Madrid', '2022', 'Q_Fucsovics_Merida_Aguilar')
('Madrid', '2021', 'Q_Zapata_Miralles_Delbonis')
('Monte_Carlo', '2021', 'Q_Koepfer_Zapata_Miralles')
('Monte_Carlo', '2021', 'R64_Davidovich_Fokina_de_Minaur')
('Madrid', '2022', 'MS031_M._Cilic_A._Zverev')
('Rome', '2022', 'R16_de_Minaur_Zverev')
('Wimbledon', '2021', 'LS011_C._Gauff_A._Kerber')
('Rogers_cup', '2022', 'R16_Kyrgios_de_Minaur')
('Cincinnati', '2021', 'R32_Monfils_de_Minaur')
('Cincinnati', '2021', 'R64_Krajinovic_de_Minaur')
('Cincinnati', '2022', 'R32_Auger-Aliassime_de_Minaur')
('Cincinnati', '2022', 'R64_Laaksonen_de_Minaur')
('Indian_Wells', '2021', 'R32_Garin_de_Minaur')
('Indian_Wells', '2021', 'R64_Vukic_de_Minaur')
('Indian_Wells', '2022', 'R16_Fritz_de_Minaur')
('Indian_Wells', '2022', 'R32_de_Minaur_Paul')
('Indian_Wells', '2022', 'R64_de_Minaur_Millman')
('Madrid', '2021', 'R16_Thiem_de_Minaur')
('Madrid', '2021', 'R32_de_Minaur_Harris')
('Madrid', '2021', 'R64_de_Minaur_Munar')
('Madrid', '2022', 'R32_de_Minaur_Sinner')
('Madrid', '2022', 'R64_de_Minaur_Martinez')
('Miami', '2021', 'R64_de_Minaur_Galan')
('Monte_Carlo', '2021', 'R64_Davidovich_Fokina_de_Minaur')
('Paris', '2021', 'R64_Popyrin_de_Minaur')
('Rogers_cup', '2021', 'R32_de_Minaur_Basilashvili')
('Rogers_cup', '2022', 'R16_Kyrgios_de_Minaur')
('Rogers_cup', '2022', 'R32_de_Minaur_Dimitrov')
('Rogers_cup', '2022', 'R64_Shapovalov_de_Minaur')
('Rome', '2021', 'R64_Mager_de_Minaur')
('Rome', '2022', 'R16_de_Minaur_Zverev')
('Rome', '2022', 'R32_de_Minaur_Paul')
('Rome', '2022', 'R64_Lajovic_de_Minaur')
('Indian_Wells', '2022', 'R32_de_Minaur_Paul')
('Rome', '2022', 'R32_de_Minaur_Paul')
('Miami', '2021', 'Q_McDonald_Cid_Subervi')
('Rogers_cup', '2022', 'R64_Shapovalov_de_Minaur')
('Madrid', '2021', 'Q_Cecchinato_Carballes_Baena')
('Cincinnati', '2021', 'R64_Krajinovic_de_Minaur')
('Indian_Wells', '2022', 'R64_de_Minaur_Millman')
('Cincinnati', '2022', 'R32_Auger-Aliassime_de_Minaur')
('Madrid', '2022', 'MS031_M._Cilic_A._Zverev')
('Rome', '2022', 'MS014_C._Garin_M._Cilic')
('Madrid', '2021', 'R32_de_Minaur_Harris')
('Rome', '2021', 'R64_Mager_de_Minaur')
('Madrid', '2021', 'R64_de_Minaur_Munar')
('Monte_Carlo', '2021', 'Q_Koepfer_Zapata_Miralles')
('Rome', '2021', 'Q_Sandgren_Carballes_Baena')
('Indian_Wells', '2021', 'R64_Carballes_Baena_Ruud')
('Indian_Wells', '2021', 'R32_Garin_de_Minaur')
('Rome', '2022', 'MS014_C._Garin_M._Cilic')
('Madrid', '2022', 'Q_Carballes_Baena_Lajovic')
('Rome', '2022', 'R64_Lajovic_de_Minaur')
('Cincinnati', '2022', 'R64_Laaksonen_de_Minaur')
('Madrid', '2022', 'R64_de_Minaur_Martinez')
('Madrid', '2021', 'Q_Carballes_Baena_Ruusuvuori')
('Madrid', '2022', 'Q_Cerundolo_Moro_Canas')
('Madrid', '2022', 'Q_Molcan_Carballes_Baena')
('Indian_Wells', '2022', '1st_Brooksby_Carballes_Baena')
('Paris', '2021', 'Q_Brooksby_Carballes_Baena')
('Indian_Wells', '2021', '1st_Olivo_Carballes_Baena')
('Indian_Wells', '2021', 'R64_Carballes_Baena_Ruud')
('Indian_Wells', '2022', '1st_Brooksby_Carballes_Baena')
('Madrid', '2021', 'Q_Carballes_Baena_Ruusuvuori')
('Madrid', '2021', 'Q_Cecchinato_Carballes_Baena')
('Madrid', '2022', 'Q_Carballes_Baena_Lajovic')
('Madrid', '2022', 'Q_Molcan_Carballes_Baena')
('Paris', '2021', 'Q_Brooksby_Carballes_Baena')
('Paris', '2021', 'Q_Van_Assche_Carballes_Baena')
('Rome', '2021', 'Q_Carballes_Baena_Brancaccio')
('Rome', '2021', 'Q_Sandgren_Carballes_Baena')
('Rome', '2021', 'R64_Carballes_Baena_Norrie')
('Miami', '2021', '1st_Galan_Seyboth_Wild')
('Miami', '2021', 'R64_de_Minaur_Galan')
('Madrid', '2021', 'Q_Travaglia_Gimeno_Valero')
('Madrid', '2021', 'Q_Travaglia_Gimeno_Valero')
('Madrid', '2022', 'R64_Gimeno_Valero_Monfils')
('Madrid', '2022', 'Q_Cerundolo_Moro_Canas')
('Madrid', '2022', 'Q_Moro_Canas_Musetti')
('Madrid', '2022', 'Q_Fucsovics_Merida_Aguilar')
('Rome', '2021', 'Q_Carballes_Baena_Brancaccio')
('Paris', '2021', 'Q_Van_Assche_Carballes_Baena')
('Miami', '2021', '1st_Galan_Seyboth_Wild')
('Miami', '2021', 'Q_McDonald_Cid_Subervi')
('Wimbledon', '2021', 'LS011_C._Gauff_A._Kerber')
('Toronto', '2022', 'SF_Gauff__Halep')

In [75]:
df_atp = pd.read_sql('SELECT match_id, surface, "PLAYER_HIT" FROM atp_matches_data', engine).drop_duplicates()

In [76]:
#df_atp.columns = ['match_id', 'surface', '']

In [77]:
df_atp

                                                match_id surface    PLAYER_HIT
0             Buenos_Aires_2026_Q_Collarini_Seyboth-Wild    clay     COLLARINI
1             Buenos_Aires_2026_Q_Collarini_Seyboth-Wild    clay  SEYBOTH WILD
6               Rotterdam_2026_Q_Medjedovic_Basilashvili    hard    MEDJEDOVIC
7               Rotterdam_2026_Q_Medjedovic_Basilashvili    hard  BASILASHVILI
10                     Rotterdam_2026_Q_Sachko_O'Connell    hard     O'CONNELL
...                                                  ...     ...           ...
32381  Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby    hard      BROOKSBY
32384          Winston_Salem_2026_R64_Landaluce_Bellucci    hard     LANDALUCE
32385          Winston_Salem_2026_R64_Landaluce_Bellucci    hard      BELLUCCI
32390      Winston_Salem_2026_R64_Shimabukuro_Kecmanovic    hard   SHIMABUKURO
32391      Winston_Salem_2026_R64_Shimabukuro_Kecmanovic    hard    KECMANOVIC

[13210 rows x 3 columns]

In [78]:
for _, row in df_atp.iterrows():
    #if not row['match_id'] in df_all.match_id.unique():
    #    continue
    if 'combined' in row['match_id']:
        continue
    pattern = re.compile(r'(.+?)_(\d{4})_(.+)')
    # Use the pattern to match and extract the partssss
    matches = pattern.match(row['match_id'])
    parts = matches.groups()

    tournament = parts[0].replace('_', ' ').strip().upper()
    if tournament == 'MONTREAL' or tournament == 'TORONTO':
        tournament = 'ROGERS CUP'
    year = parts[1]
    
    if tournament in grass_tournaments and row['surface'] != 'grass':
        row['surface'] = 'grass'
        #print(row['match_id'], 'grass')
    if tournament in clay_tournaments and row['surface'] != 'clay':
        row['surface'] = 'clay'
        #print(row['match_id'], 'clay')
    if tournament == 'RG':
        tournament = 'ROLAND GARROS'
    if tournament == 'AO':
        tournament = 'AUSTRALIAN OPEN'
   
    
    try:
        round_number, _, _ = parts[2].replace('Haddad_Maia', 'Haddad-Maia').replace('Carreno_Busta', 'Carreno-Busta').replace('Bautista_Agut', 'Bautista-Agut').replace('van_de_Zandschulp', 'van-de-Zandschulp').replace('Davidovich_Fokina', 'Davidovich-Fokina').split('_')
        data.append({
            'PLAYER': row['PLAYER_HIT'],
            'TOURNAMENT': tournament.replace(' ', '-').replace('_', '-'),
            'YEAR': year,
            'ROUND': round_number,
            'SURFACE': row['surface'],
            'FORMAT': 'HE',
            'match_id': row['match_id'],
        })
    except:
        print(parts)
        continue
import json
with open('/Users/marinkreso/Documents/gsa_post_match/nicegui_dir/new_code4/all_data3.json', 'w') as f:
    json.dump(data, f, indent=4)

('Stuttgart', '2026', 'Alejandro_Davidovich_Fokina_v_Mattia_Bellucci_2026-06-08_tracking_data')
('Stuttgart', '2026', 'Alejandro_Davidovich_Fokina_v_Mattia_Bellucci_2026-06-08_tracking_data')
('Stuttgart', '2026', 'Gauthier_Onclin_v_Fabian_Marozsan_2026-06-08_tracking_data')
('Stuttgart', '2026', 'Gauthier_Onclin_v_Fabian_Marozsan_2026-06-08_tracking_data')
('AO', '2016', '4thMurray_Tomic')
('AO', '2016', '4thMurray_Tomic')
('Cincinnati', '2021', 'R32_Monfils_de_Minaur')
('Cincinnati', '2021', 'R32_Monfils_de_Minaur')
('Cincinnati', '2021', 'R64_Krajinovic_de_Minaur')
('Cincinnati', '2021', 'R64_Krajinovic_de_Minaur')
('Cincinnati', '2022', 'R32_Auger-Aliassime_de_Minaur')
('Cincinnati', '2022', 'R32_Auger-Aliassime_de_Minaur')
('Cincinnati', '2022', 'R64_Laaksonen_de_Minaur')
('Cincinnati', '2022', 'R64_Laaksonen_de_Minaur')
('Halle', '2016', '2nd_Zverev_Becker_RET')
('Halle', '2016', '2nd_Zverev_Becker_RET')
('Indian_Wells', '2021', '1st_Olivo_Carballes_Baena')
('Indian_Wells', '2021', '1st_Olivo_Carballes_Baena')
('Indian_Wells', '2021', 'R32_Garin_de_Minaur')
('Indian_Wells', '2021', 'R32_Garin_de_Minaur')
('Indian_Wells', '2021', 'R64_Carballes_Baena_Ruud')
('Indian_Wells', '2021', 'R64_Carballes_Baena_Ruud')
('Indian_Wells', '2021', 'R64_Vukic_de_Minaur')
('Indian_Wells', '2021', 'R64_Vukic_de_Minaur')
('Indian_Wells', '2022', '1st_Brooksby_Carballes_Baena')
('Indian_Wells', '2022', '1st_Brooksby_Carballes_Baena')
('Indian_Wells', '2022', 'R16_Fritz_de_Minaur')
('Indian_Wells', '2022', 'R16_Fritz_de_Minaur')
('Indian_Wells', '2022', 'R32_de_Minaur_Paul')
('Indian_Wells', '2022', 'R32_de_Minaur_Paul')
('Indian_Wells', '2022', 'R64_de_Minaur_Millman')
('Indian_Wells', '2022', 'R64_de_Minaur_Millman')
('Madrid', '2021', 'Q_Carballes_Baena_Ruusuvuori')
('Madrid', '2021', 'Q_Carballes_Baena_Ruusuvuori')
('Madrid', '2021', 'Q_Cecchinato_Carballes_Baena')
('Madrid', '2021', 'Q_Cecchinato_Carballes_Baena')
('Madrid', '2021', 'Q_Travaglia_Gimeno_Valero')
('Madrid', '2021', 'Q_Travaglia_Gimeno_Valero')
('Madrid', '2021', 'Q_Zapata_Miralles_Delbonis')
('Madrid', '2021', 'Q_Zapata_Miralles_Delbonis')
('Madrid', '2021', 'R16_Thiem_de_Minaur')
('Madrid', '2021', 'R16_Thiem_de_Minaur')
('Madrid', '2021', 'R32_de_Minaur_Harris')
('Madrid', '2021', 'R32_de_Minaur_Harris')
('Madrid', '2021', 'R64_de_Minaur_Munar')
('Madrid', '2021', 'R64_de_Minaur_Munar')
('Madrid', '2022', 'MS031_M._Cilic_A._Zverev')
('Madrid', '2022', 'MS031_M._Cilic_A._Zverev')
('Madrid', '2022', 'Q_Carballes_Baena_Lajovic')
('Madrid', '2022', 'Q_Carballes_Baena_Lajovic')
('Madrid', '2022', 'Q_Fucsovics_Merida_Aguilar')
('Madrid', '2022', 'Q_Fucsovics_Merida_Aguilar')
('Madrid', '2022', 'Q_Molcan_Carballes_Baena')
('Madrid', '2022', 'Q_Molcan_Carballes_Baena')
('Madrid', '2022', 'R32_de_Minaur_Sinner')
('Madrid', '2022', 'R32_de_Minaur_Sinner')
('Madrid', '2022', 'R64_de_Minaur_Martinez')
('Madrid', '2022', 'R64_de_Minaur_Martinez')
('Madrid', '2022', 'R64_Gimeno_Valero_Monfils')
('Madrid', '2022', 'R64_Gimeno_Valero_Monfils')
('Miami', '2021', '1st_Galan_Seyboth_Wild')
('Miami', '2021', '1st_Galan_Seyboth_Wild')
('Miami', '2021', 'Q_McDonald_Cid_Subervi')
('Miami', '2021', 'Q_McDonald_Cid_Subervi')
('Miami', '2021', 'R64_de_Minaur_Galan')
('Miami', '2021', 'R64_de_Minaur_Galan')
('Miami', '2022', '1st_Carballes_Baena_Goffin')
('Miami', '2022', '1st_Carballes_Baena_Goffin')
('Miami', '2022', 'Q_Munar_Seyboth_Wild')
('Miami', '2022', 'Q_Munar_Seyboth_Wild')
('Miami', '2022', 'R64_Thompson_de_Minaur')
('Miami', '2022', 'R64_Thompson_de_Minaur')
('Paris', '2021', 'Q_Brooksby_Carballes_Baena')
('Paris', '2021', 'Q_Brooksby_Carballes_Baena')
('Paris', '2021', 'Q_Van_Assche_Carballes_Baena')
('Paris', '2021', 'Q_Van_Assche_Carballes_Baena')
('Paris', '2021', 'R64_Popyrin_de_Minaur')
('Paris', '2021', 'R64_Popyrin_de_Minaur')
('Rogers_cup', '2021', 'R32_de_Minaur_Basilashvili')
('Rogers_cup', '2021', 'R32_de_Minaur_Basilashvili')
('Rogers_cup', '2022', 'R16_Kyrgios_de_Minaur')
('Rogers_cup', '2022', 'R16_Kyrgios_de_Minaur')
('Rogers_cup', '2022', 'R32_de_Minaur_Dimitrov')
('Rogers_cup', '2022', 'R32_de_Minaur_Dimitrov')
('Rogers_cup', '2022', 'R64_Shapovalov_de_Minaur')
('Rogers_cup', '2022', 'R64_Shapovalov_de_Minaur')
('Rome', '2021', 'Q_Carballes_Baena_Brancaccio')
('Rome', '2021', 'Q_Carballes_Baena_Brancaccio')
('Rome', '2021', 'Q_Sandgren_Carballes_Baena')
('Rome', '2021', 'Q_Sandgren_Carballes_Baena')
('Rome', '2021', 'R64_Carballes_Baena_Norrie')
('Rome', '2021', 'R64_Carballes_Baena_Norrie')
('Rome', '2021', 'R64_Mager_de_Minaur')
('Rome', '2021', 'R64_Mager_de_Minaur')
('Rome', '2022', 'MS014_C._Garin_M._Cilic')
('Rome', '2022', 'MS014_C._Garin_M._Cilic')
('Rome', '2022', 'R16_de_Minaur_Zverev')
('Rome', '2022', 'R16_de_Minaur_Zverev')
('Rome', '2022', 'R32_de_Minaur_Paul')
('Rome', '2022', 'R32_de_Minaur_Paul')
('Rome', '2022', 'R64_Lajovic_de_Minaur')
('Rome', '2022', 'R64_Lajovic_de_Minaur')
('Monte_Carlo', '2021', 'Q_Koepfer_Zapata_Miralles')
('Monte_Carlo', '2021', 'Q_Koepfer_Zapata_Miralles')
('Monte_Carlo', '2021', 'R64_Davidovich_Fokina_de_Minaur')
('Monte_Carlo', '2021', 'R64_Davidovich_Fokina_de_Minaur')
('Monte_Carlo', '2022', 'Q_Cressy_Van_Assche')
('Monte_Carlo', '2022', 'Q_Cressy_Van_Assche')
('Monte_Carlo', '2022', 'Q_Kwon_Zapata_Miralles')
('Monte_Carlo', '2022', 'Q_Kwon_Zapata_Miralles')
('Monte_Carlo', '2022', 'Q_Zapata_Miralles_Sousa')
('Monte_Carlo', '2022', 'Q_Zapata_Miralles_Sousa')
('Monte_Carlo', '2022', 'R32_Rublev_de_Minaur')
('Monte_Carlo', '2022', 'R32_Rublev_de_Minaur')
('Monte_Carlo', '2022', 'R64_de_Minaur_Zapata_Miralles')
('Monte_Carlo', '2022', 'R64_de_Minaur_Zapata_Miralles')
('Monte-Carlo', '2023', '2022_SF_Sinner_Rune')
('Monte-Carlo', '2023', '2022_SF_Sinner_Rune')

In [79]:
data

[{'PLAYER': 'FILS',
  'OPPONENT': 'TIAFOE',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'F',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_F_Fils_Tiafoe'},
 {'PLAYER': 'TIAFOE',
  'OPPONENT': 'FILS',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'F',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_F_Fils_Tiafoe'},
 {'PLAYER': 'MPETSHI PERRICARD',
  'OPPONENT': 'BROOKSBY',
  'TOURNAMENT': 'WINSTON-SALEM',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby'},
 {'PLAYER': 'BROOKSBY',
  'OPPONENT': 'MPETSHI PERRICARD',
  'TOURNAMENT': 'WINSTON-SALEM',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Winston_Salem_2026_R64_Mpetshi-Perricard_Brooksby'},
 {'PLAYER': 'KECMANOVIC',
  'OPPONENT': 'SHIMABUKURO',
  'TOURNAMENT': 'WINSTON-SALEM',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Winston_Salem_2026_R64_Shimabukuro_Kecmanovic'},
 {'PLAYER': 'SHIMABUKURO',
  'OPPONENT': 'KECMANOVIC',
  'TOURNAMENT': 'WINSTON-SALEM',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Winston_Salem_2026_R64_Shimabukuro_Kecmanovic'},
 {'PLAYER': 'SWIATEK',
  'OPPONENT': 'PEGULA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_SF_Pegula_Swiatek'},
 {'PLAYER': 'PEGULA',
  'OPPONENT': 'SWIATEK',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_SF_Pegula_Swiatek'},
 {'PLAYER': 'FILS',
  'OPPONENT': 'COBOLLI',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_SF_Cobolli_Fils'},
 {'PLAYER': 'COBOLLI',
  'OPPONENT': 'FILS',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_SF_Cobolli_Fils'},
 {'PLAYER': 'NAKASHIMA',
  'OPPONENT': 'TIAFOE',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_SF_Nakashima_Tiafoe'},
 {'PLAYER': 'TIAFOE',
  'OPPONENT': 'NAKASHIMA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_SF_Nakashima_Tiafoe'},
 {'PLAYER': 'FRITZ',
  'OPPONENT': 'NAKASHIMA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'QF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_QF_Fritz_Nakashima'},
 {'PLAYER': 'NAKASHIMA',
  'OPPONENT': 'FRITZ',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'QF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_QF_Fritz_Nakashima'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'MOUTET',
  'TOURNAMENT': 'BARCELONA',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Barcelona_2026_R32_Buse_Moutet'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'WALTON',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R64_Walton_Buse'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'PAUL',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'F',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_F_Buse_Paul'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'HUMBERT',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'QF',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_QF_Buse_Humbert'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'GASTON',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_Q_Buse_Gaston'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'MCDONALD',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_Q_Buse_Mcdonald'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'COBOLLI',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_R32_Cobolli_Buse'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'KOVACEVIC',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_SF_Kovacevic_Buse'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'DRAXL',
  'TOURNAMENT': 'INDIAN-WELLS',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Indian-Wells_2026_Q_Buse_Draxl'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'HIJIKATA',
  'TOURNAMENT': 'INDIAN-WELLS',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Indian-Wells_2026_Q_Buse_Hijikata'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'FELDBAUSCH',
  'TOURNAMENT': 'KITZBUHEL',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Kitzbuhel_2026_R16_Feldbausch_Buse'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'KOPRIVA',
  'TOURNAMENT': 'KITZBUHEL',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Kitzbuhel_2026_R32_Kopriva_Buse'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'MANNARINO',
  'TOURNAMENT': 'MADRID',
  'YEAR': '2026',
  'ROUND': '1st',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Madrid_2026_1st_Buse_Mannarino'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'KOPRIVA',
  'TOURNAMENT': 'MALLORCA',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'grass',
  'FORMAT': 'HE',
  'match_id': 'Mallorca_2026_R16_Kopriva_Buse'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'UGO CARABELLI',
  'TOURNAMENT': 'MARRAKECH',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Marrakech_2026_R16_Buse_Ugo-Carabelli'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'BERRETTINI',
  'TOURNAMENT': 'MARRAKECH',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Marrakech_2026_R32_Buse_Berrettini'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'DZUMHUR',
  'TOURNAMENT': 'MIAMI',
  'YEAR': '2026',
  'ROUND': '1st',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Miami_2026_1st_Buse_Dzumhur'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'ECHARGUI',
  'TOURNAMENT': 'MIAMI',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Miami_2026_Q_Buse_Echargui'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'WONG',
  'TOURNAMENT': 'MIAMI',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Miami_2026_Q_Buse_Wong'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'GOFFIN',
  'TOURNAMENT': 'MONTE-CARLO',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Monte_Carlo_2026_Q_Buse_Goffin'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'GIRON',
  'TOURNAMENT': 'QUEENS',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'grass',
  'FORMAT': 'HE',
  'match_id': 'Queens_2026_R32_Buse_Giron'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'BERRETTINI',
  'TOURNAMENT': 'RIO',
  'YEAR': '2026',
  'ROUND': 'QF',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rio_2026_QF_Buse_Berrettini'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'MARCONDES',
  'TOURNAMENT': 'RIO',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rio_2026_R32_Marcondes_Buse'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'TABILO',
  'TOURNAMENT': 'RIO',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rio_2026_SF_Tabilo_Buse'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'NORRIE',
  'TOURNAMENT': 'ROGERS-CUP',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Rogers_cup_2026_R64_Buse_Norrie'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'SONEGO',
  'TOURNAMENT': 'ROME',
  'YEAR': '2026',
  'ROUND': '1st',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rome_2026_1st_Sonego_Buse'},
 {'PLAYER': 'BUSE',
  'OPPONENT': 'TIAFOE',
  'TOURNAMENT': 'ROME',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rome_2026_R64_Tiafoe_Buse'},
 {'PLAYER': 'MOUTET',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'BARCELONA',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Barcelona_2026_R32_Buse_Moutet'},
 {'PLAYER': 'WALTON',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R64_Walton_Buse'},
 {'PLAYER': 'PAUL',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'F',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_F_Buse_Paul'},
 {'PLAYER': 'HUMBERT',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'QF',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_QF_Buse_Humbert'},
 {'PLAYER': 'GASTON',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_Q_Buse_Gaston'},
 {'PLAYER': 'MCDONALD',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_Q_Buse_Mcdonald'},
 {'PLAYER': 'COBOLLI',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_R32_Cobolli_Buse'},
 {'PLAYER': 'KOVACEVIC',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'HAMBURG',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Hamburg_2026_SF_Kovacevic_Buse'},
 {'PLAYER': 'DRAXL',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'INDIAN-WELLS',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Indian-Wells_2026_Q_Buse_Draxl'},
 {'PLAYER': 'HIJIKATA',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'INDIAN-WELLS',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Indian-Wells_2026_Q_Buse_Hijikata'},
 {'PLAYER': 'FELDBAUSCH',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'KITZBUHEL',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Kitzbuhel_2026_R16_Feldbausch_Buse'},
 {'PLAYER': 'KOPRIVA',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'KITZBUHEL',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Kitzbuhel_2026_R32_Kopriva_Buse'},
 {'PLAYER': 'KOPRIVA',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'MALLORCA',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'grass',
  'FORMAT': 'HE',
  'match_id': 'Mallorca_2026_R16_Kopriva_Buse'},
 {'PLAYER': 'MANNARINO',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'MADRID',
  'YEAR': '2026',
  'ROUND': '1st',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Madrid_2026_1st_Buse_Mannarino'},
 {'PLAYER': 'UGO CARABELLI',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'MARRAKECH',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Marrakech_2026_R16_Buse_Ugo-Carabelli'},
 {'PLAYER': 'BERRETTINI',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'MARRAKECH',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Marrakech_2026_R32_Buse_Berrettini'},
 {'PLAYER': 'BERRETTINI',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'RIO',
  'YEAR': '2026',
  'ROUND': 'QF',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rio_2026_QF_Buse_Berrettini'},
 {'PLAYER': 'DZUMHUR',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'MIAMI',
  'YEAR': '2026',
  'ROUND': '1st',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Miami_2026_1st_Buse_Dzumhur'},
 {'PLAYER': 'ECHARGUI',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'MIAMI',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Miami_2026_Q_Buse_Echargui'},
 {'PLAYER': 'WONG',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'MIAMI',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Miami_2026_Q_Buse_Wong'},
 {'PLAYER': 'GOFFIN',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'MONTE-CARLO',
  'YEAR': '2026',
  'ROUND': 'Q',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Monte_Carlo_2026_Q_Buse_Goffin'},
 {'PLAYER': 'GIRON',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'QUEENS',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'grass',
  'FORMAT': 'HE',
  'match_id': 'Queens_2026_R32_Buse_Giron'},
 {'PLAYER': 'MARCONDES',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'RIO',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rio_2026_R32_Marcondes_Buse'},
 {'PLAYER': 'TABILO',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'RIO',
  'YEAR': '2026',
  'ROUND': 'SF',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rio_2026_SF_Tabilo_Buse'},
 {'PLAYER': 'NORRIE',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'ROGERS-CUP',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Rogers_cup_2026_R64_Buse_Norrie'},
 {'PLAYER': 'SONEGO',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'ROME',
  'YEAR': '2026',
  'ROUND': '1st',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rome_2026_1st_Sonego_Buse'},
 {'PLAYER': 'TIAFOE',
  'OPPONENT': 'BUSE',
  'TOURNAMENT': 'ROME',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'clay',
  'FORMAT': 'HE',
  'match_id': 'Rome_2026_R64_Tiafoe_Buse'},
 {'PLAYER': 'FILS',
  'OPPONENT': 'TIRANTE',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'QF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_QF_Tirante_Fils'},
 {'PLAYER': 'TIRANTE',
  'OPPONENT': 'FILS',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'QF',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_QF_Tirante_Fils'},
 {'PLAYER': 'SHNAIDER',
  'OPPONENT': 'RYBAKINA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Shnaider_Rybakina'},
 {'PLAYER': 'RYBAKINA',
  'OPPONENT': 'SHNAIDER',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Shnaider_Rybakina'},
 {'PLAYER': 'SWIATEK',
  'OPPONENT': 'PARRY',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Swiatek_Parry'},
 {'PLAYER': 'PARRY',
  'OPPONENT': 'SWIATEK',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Swiatek_Parry'},
 {'PLAYER': 'NAKASHIMA',
  'OPPONENT': 'BORGES',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Borges_Nakashima'},
 {'PLAYER': 'BORGES',
  'OPPONENT': 'NAKASHIMA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Borges_Nakashima'},
 {'PLAYER': 'FILS',
  'OPPONENT': 'DE MINAUR',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Fils_de-Minaur'},
 {'PLAYER': 'DE MINAUR',
  'OPPONENT': 'FILS',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Fils_de-Minaur'},
 {'PLAYER': 'MENSIK',
  'OPPONENT': 'TIRANTE',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Tirante_Mensik'},
 {'PLAYER': 'TIRANTE',
  'OPPONENT': 'MENSIK',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R16',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R16_Tirante_Mensik'},
 {'PLAYER': 'NAKASHIMA',
  'OPPONENT': 'MEDVEDEV',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Nakashima_Medvedev'},
 {'PLAYER': 'MEDVEDEV',
  'OPPONENT': 'NAKASHIMA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Nakashima_Medvedev'},
 {'PLAYER': 'NAVARRO',
  'OPPONENT': 'PEGULA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Navarro_Pegula'},
 {'PLAYER': 'PEGULA',
  'OPPONENT': 'NAVARRO',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Navarro_Pegula'},
 {'PLAYER': 'BLOCKX',
  'OPPONENT': 'COBOLLI',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Blockx_Cobolli'},
 {'PLAYER': 'COBOLLI',
  'OPPONENT': 'BLOCKX',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Blockx_Cobolli'},
 {'PLAYER': 'MENSIK',
  'OPPONENT': 'HIJIKATA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Hijikata_Mensik'},
 {'PLAYER': 'HIJIKATA',
  'OPPONENT': 'MENSIK',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Hijikata_Mensik'},
 {'PLAYER': 'FILS',
  'OPPONENT': 'LEHECKA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Lehecka_Fils'},
 {'PLAYER': 'LEHECKA',
  'OPPONENT': 'FILS',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Lehecka_Fils'},
 {'PLAYER': 'RYBAKINA',
  'OPPONENT': 'FRECH',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Frech_Rybakina'},
 {'PLAYER': 'FRECH',
  'OPPONENT': 'RYBAKINA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Frech_Rybakina'},
 {'PLAYER': 'SWIATEK',
  'OPPONENT': 'SAKKARI',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Swiatek_Sakkari'},
 {'PLAYER': 'SAKKARI',
  'OPPONENT': 'SWIATEK',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R32',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R32_Swiatek_Sakkari'},
 {'PLAYER': 'NAVARRO',
  'OPPONENT': 'KALININA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R64_Navarro_Kalinina'},
 {'PLAYER': 'KALININA',
  'OPPONENT': 'NAVARRO',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R64_Navarro_Kalinina'},
 {'PLAYER': 'SWIATEK',
  'OPPONENT': 'ARANGO',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R64_Swiatek_Arango'},
 {'PLAYER': 'ARANGO',
  'OPPONENT': 'SWIATEK',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R64_Swiatek_Arango'},
 {'PLAYER': 'RYBAKINA',
  'OPPONENT': 'TOWNSEND',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',
  'match_id': 'Cincinnati_2026_R64_Townsend_Rybakina'},
 {'PLAYER': 'TOWNSEND',
  'OPPONENT': 'RYBAKINA',
  'TOURNAMENT': 'CINCINNATI',
  'YEAR': '2026',
  'ROUND': 'R64',
  'SURFACE': 'hard',
  'FORMAT': 'HE',

In [80]:
for d in data:
    if d['PLAYER'] == 'BAEZ' and 'rio' in d['match_id'].lower():
        print(d)

{'PLAYER': 'BAEZ', 'OPPONENT': 'NAVONE', 'TOURNAMENT': 'RIO', 'YEAR': '2025', 'ROUND': 'R16', 'SURFACE': 'clay', 'FORMAT': 'HE', 'match_id': 'Rio_2025_R16_Baez_Navone'}
{'PLAYER': 'BAEZ', 'OPPONENT': 'FARIA', 'TOURNAMENT': 'RIO', 'YEAR': '2026', 'ROUND': 'R32', 'SURFACE': 'clay', 'FORMAT': 'HE', 'match_id': 'Rio_2026_R32_Faria_Baez'}
{'PLAYER': 'BAEZ', 'OPPONENT': 'MULLER', 'TOURNAMENT': 'RIO-DE-JANEIRO', 'YEAR': '2025', 'ROUND': 'F', 'SURFACE': 'hard', 'FORMAT': 'HE', 'match_id': 'Rio_de_Janeiro_2025_F_Muller_Baez'}
{'PLAYER': 'BAEZ', 'OPPONENT': 'TSENG', 'TOURNAMENT': 'RIO-DE-JANEIRO', 'YEAR': '2025', 'ROUND': 'QF', 'SURFACE': 'hard', 'FORMAT': 'HE', 'match_id': 'Rio_de_Janeiro_2025_QF_Baez_Tseng'}
{'PLAYER': 'BAEZ', 'OPPONENT': 'NAVONE', 'TOURNAMENT': 'RIO-DE-JANEIRO', 'YEAR': '2025', 'ROUND': 'R16', 'SURFACE': 'hard', 'FORMAT': 'HE', 'match_id': 'Rio_de_Janeiro_2025_R16_Baez_Navone'}
{'PLAYER': 'BAEZ', 'OPPONENT': 'UGO CARABELLI', 'TOURNAMENT': 'RIO-DE-JANEIRO', 'YEAR': '2025', 'ROUND': 'SF', 'SURFACE': 'hard', 'FORMAT': 'HE', 'match_id': 'Rio_de_Janeiro_2025_SF_Baez_Ugo-Carabelli'}
{'PLAYER': 'BAEZ', 'TOURNAMENT': 'RIO', 'YEAR': '2026', 'ROUND': 'R32', 'SURFACE': 'clay', 'FORMAT': 'HE', 'match_id': 'Rio_2026_R32_Faria_Baez'}
{'PLAYER': 'BAEZ', 'TOURNAMENT': 'RIO', 'YEAR': '2025', 'ROUND': 'R16', 'SURFACE': 'clay', 'FORMAT': 'HE', 'match_id': 'Rio_2025_R16_Baez_Navone'}
{'PLAYER': 'BAEZ', 'TOURNAMENT': 'RIO-DE-JANEIRO', 'YEAR': '2025', 'ROUND': 'R16', 'SURFACE': 'clay', 'FORMAT': 'HE', 'match_id': 'Rio_de_Janeiro_2025_R16_Baez_Navone'}
{'PLAYER': 'BAEZ', 'TOURNAMENT': 'RIO-DE-JANEIRO', 'YEAR': '2025', 'ROUND': 'QF', 'SURFACE': 'clay', 'FORMAT': 'HE', 'match_id': 'Rio_de_Janeiro_2025_QF_Baez_Tseng'}
{'PLAYER': 'BAEZ', 'TOURNAMENT': 'RIO-DE-JANEIRO', 'YEAR': '2025', 'ROUND': 'F', 'SURFACE': 'clay', 'FORMAT': 'HE', 'match_id': 'Rio_de_Janeiro_2025_F_Muller_Baez'}
{'PLAYER': 'BAEZ', 'TOURNAMENT': 'RIO-DE-JANEIRO', 'YEAR': '2025', 'ROUND': 'SF', 'SURFACE': 'clay', 'FORMAT': 'HE', 'match_id': 'Rio_de_Janeiro_2025_SF_Baez_Ugo-Carabelli'}